import {validateServiceRequest} from './contracts.mjs';
import {OPERATION_SCOPE} from './constants.mjs';
import {frozenClone} from './boundary.mjs';
const READABLE={owner:['active','terminal','archived'],reviewer:['active','terminal','archived'],operator:['active','terminal'],reader:['active','terminal','archived']};
function decision(allowed,reason,request){return frozenClone({schemaVersion:'audit-phase9-authorization-decision-v1',allowed,reason,operation:request.operation,tenantId:request.tenantId,workspaceId:request.workspaceId,campaignId:request.campaignId,forkId:request.forkId,requesterId:request.requesterId});}
export function authorizePhase78Operation(requestInput,{forkState=null,accessContext=null,allowCreate=false}={}){const request=validateServiceRequest(requestInput),scope=OPERATION_SCOPE[request.operation];if(!request.scopes.includes(scope))return decision(false,'scope_missing',request);
 if(request.operation.startsWith('fork.')){if(request.operation==='fork.create'&&allowCreate&&forkState===null)return decision(true,'allowed',request);if(!forkState)return decision(false,'resource_hidden',request);if(forkState.tenantId!==request.tenantId)return decision(false,'tenant_mismatch',request);if(forkState.forkId!==request.forkId)return decision(false,'resource_hidden',request);return decision(true,'allowed',request);}
 if(!accessContext)return decision(false,'resource_hidden',request);if(accessContext.tenantId!==request.tenantId)return decision(false,'tenant_mismatch',request);if(accessContext.workspaceId!==request.workspaceId)return decision(false,'workspace_mismatch',request);if(request.campaignId!==null&&accessContext.campaignId!==request.campaignId)return decision(false,'resource_hidden',request);if(accessContext.requesterId&&accessContext.requesterId!==request.requesterId)return decision(false,'requester_mismatch',request);if(!Array.isArray(accessContext.scopes)||!accessContext.scopes.includes(scope))return decision(false,'scope_missing',request);
 const read=request.operation.endsWith('.read')||request.operation==='provenance.read';if(read){if(!READABLE[accessContext.campaignRole]?.includes(accessContext.campaignState))return decision(false,'role_state_denied',request);}else if(accessContext.campaignState!=='active'||!['owner','operator'].includes(accessContext.campaignRole))return decision(false,'role_state_denied',request);
 return decision(true,'allowed',request);}
