import {validateServiceRequest} from './contracts.mjs';
import {TERMINAL_STATES} from './constants.mjs';
import {exactKeys,canonicalClone,digest,integer,identifier,digestArray,sha256,frozenClone,fail} from './boundary.mjs';
const SUMMARY={
 'fork.create':{classA:3,classB:1,free:0},'fork.read':{classA:0,classB:2,free:0},'fork.action':{classA:2,classB:2,free:0},'fork.checkpoint':{classA:3,classB:3,free:0},'fork.export':{classA:2,classB:3,free:0},'fork.delete':{classA:3,classB:3,free:3},
 'campaign.create':{classA:3,classB:2,free:0},'campaign.read':{classA:0,classB:2,free:0},'share.create':{classA:2,classB:2,free:0},'share.revoke':{classA:2,classB:2,free:0},'merge.create':{classA:4,classB:4,free:0},'merge.read':{classA:0,classB:2,free:0},'provenance.read':{classA:0,classB:2,free:0},'report.read':{classA:0,classB:2,free:0},'report.publish':{classA:3,classB:3,free:0}};
function readOnly(operation){return operation.endsWith('.read')||operation==='provenance.read';}
export function planPhase78Operation({request:requestInput,authorization,current}){const request=validateServiceRequest(requestInput);if(!authorization?.allowed)fail('unauthorized','$');if(request.expectedVersion!==null){if(!current||current.version!==request.expectedVersion||current.etag!==request.expectedEtag)fail('stale_state','$.current');}if(current&&TERMINAL_STATES.includes(current.state)&&!readOnly(request.operation))fail('terminal_state','$.current.state');const nextVersion=readOnly(request.operation)?(current?.version??null):(current?.version??0)+1;const external=request.operation==='fork.create'&&request.payload.adapterKind==='external';const resultStatus=external?'awaiting_executor':readOnly(request.operation)?'succeeded':'accepted';const steps=[{kind:'read',class:'class-b',target:'current'},{kind:'immutable-write',class:'class-a',target:'request-event'},{kind:'immutable-write',class:'class-a',target:'result-event'},{kind:'cas-write',class:'class-a',target:'current-pointer'}];const core={schemaVersion:'audit-phase9-orchestration-plan-v1',requestId:request.requestId,requestDigest:request.requestDigest,operation:request.operation,tenantId:request.tenantId,workspaceId:request.workspaceId,campaignId:request.campaignId,forkId:request.forkId,mergeId:request.mergeId,currentVersion:current?.version??null,nextVersion,resultStatus,executionEnabled:false,terminalProtection:true,idempotencyKey:request.idempotencyKey,steps,operationSummary:SUMMARY[request.operation],usesPrefixListing:false};return frozenClone({...core,planDigest:sha256(core)});}
export function createRetryPlan(input){const v=exactKeys(input,['request','current','completedWrites','failedStep'],'$'),request=v.request;if(!request||typeof request!=='object')fail('invalid_request','$.request');let expected;try{expected=validateServiceRequest(request);}catch(error){if(error.code==='digest_mismatch')fail('request_digest_mismatch','$.request.requestDigest');throw error;}if(expected.requestDigest!==request.requestDigest)fail('request_digest_mismatch','$.request.requestDigest');const current=canonicalClone(v.current),completedWrites=digestArray(v.completedWrites,'$.completedWrites',64),failedStep=identifier(v.failedStep,'$.failedStep');if(expected.expectedVersion!==null&&(current.version!==expected.expectedVersion||current.etag!==expected.expectedEtag))fail('stale_state','$.current');const core={schemaVersion:'audit-phase9-retry-plan-v1',requestId:expected.requestId,requestDigest:expected.requestDigest,currentVersion:integer(current.version,'$.current.version',0),currentEtag:digest(current.etag,'$.current.etag'),currentState:identifier(current.state,'$.current.state'),completedWrites,failedStep,maxAttempts:4,retrySafe:true,retryOrder:['immutable-missing','mutable-pointer-last'],executionEnabled:false};return frozenClone({...core,retryPlanId:`retry-${sha256(core).slice(7,31)}`,retryDigest:sha256(core)});}
