import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createGitHubActionsTransport } from '../apps/audit-github-direct-cli/src/github-actions-transport.mjs';
import { createDirectRequest,sha256 } from '../packages/audit-github-direct-protocol/src/index.mjs';
import { planCheckPublication,planCommentPublication,planStatusPublication } from '../packages/audit-github-direct-adapter/src/index.mjs';
function response(status,body){return {status,ok:status>=200&&status<300,json:async()=>body};}
const at='2026-08-01T23:40:00.000Z';
const request=createDirectRequest({repositoryId:123,installationId:123,repositoryFullName:'curveyield/contract-automation',requesterId:'user-1',policyVersion:'direct-policy-v1',profileId:'hardhat-test-v1',parserVersion:'hardhat-test-parser-v1',resultContractVersion:'phase5-tool-result-v1',reportContractVersion:'audit-report-v1',targetCommitSha:'a'.repeat(40),requestedAt:at,idempotencyKey:'transport-publication'});
const identity={repositoryId:123,installationId:123,repositoryFullName:request.repositoryFullName,targetCommitSha:request.targetCommitSha};
test('transport uses fixed api.github.com URLs and token only in request headers',async()=>{const calls=[];const wanted=`audit-direct-result-${identity.repositoryId}-${identity.targetCommitSha}`;const fetchImpl=async(url,init)=>{calls.push({url,init});if(url.endsWith('/actions/artifacts?per_page=100'))return response(200,{artifacts:[{id:1,name:wanted,size_in_bytes:1,digest:`sha256:${'1'.repeat(64)}`,expired:false,created_at:at,expires_at:'2026-08-02T00:40:00.000Z'}]});return response(200,{id:123,full_name:'CurveYield/Contract-Automation',sha:identity.targetCommitSha});};const transport=createGitHubActionsTransport({tokenProvider:()=> 'ghs_secret',fetchImpl,issueNumber:115});assert.deepEqual(await transport.getRepository(identity),{repositoryId:123,fullName:'CurveYield/Contract-Automation'});await transport.getCommit(identity);assert.equal(calls[0].init.headers.authorization,'Bearer ghs_secret');assert.doesNotMatch(JSON.stringify(await transport.getArtifactMetadata({...identity})),/ghs_secret|bearer|authorization/i);});
test('contents reads derive target/control refs and reject unsafe paths',async()=>{const calls=[];const encoded=Buffer.from(JSON.stringify({ok:true})).toString('base64');const fetchImpl=async(url)=>{calls.push(url);return response(200,{sha:'b'.repeat(40),content:encoded});};const transport=createGitHubActionsTransport({tokenProvider:()=> 'token',fetchImpl,issueNumber:115});await transport.getContents({...identity,path:'contracts/A.sol'});await transport.getContents({...identity,path:'.audit-direct/v1/current/job.json'});assert.match(calls[0],new RegExp(`ref=${identity.targetCommitSha}`));assert.match(calls[1],/ref=audit-direct%2Fcontrol-v1/);await assert.rejects(()=>transport.getContents({...identity,path:'../../secret'}),{code:'unsafe_path'});});
test('transport immutable create and CAS are idempotent/conflict-safe',async()=>{let existing=null;const fetchImpl=async(_url,init)=>{if(init.method==='GET')return existing===null?response(404,null):response(200,{sha:existing.sha,content:Buffer.from(JSON.stringify(existing.content)).toString('base64')});existing={sha:'c'.repeat(40),content:JSON.parse(Buffer.from(JSON.parse(init.body).content,'base64').toString('utf8'))};return response(200,{content:{sha:existing.sha},commit:{sha:'d'.repeat(40)}});};const transport=createGitHubActionsTransport({tokenProvider:()=> 'token',fetchImpl,issueNumber:115});const content={x:1},create={schemaVersion:'github-direct-ledger-mutation-v1',modeId:'github-direct-audit-v1',branch:'audit-direct/control-v1',operation:'create-immutable',path:'.audit-direct/v1/requests/job.json',content,contentDigest:sha256(content),expectedBlobSha:null,nextContentBlobSha:sha256(content).slice(7,47),sideEffects:false,usesPrefixListing:false};assert.equal((await transport.applyLedgerMutation({...identity,mutation:create})).applied,true);assert.equal((await transport.applyLedgerMutation({...identity,mutation:create})).applied,true);const cas={...create,operation:'update-cas',expectedBlobSha:'0'.repeat(40),content:{x:2}};await assert.rejects(()=>transport.applyLedgerMutation({...identity,mutation:cas}),{code:'stale_blob_sha'});});
async function replayCase(plan,listingPath,listingResponse){let journal=null,failJournal=true,posts=0;const fetchImpl=async(url,init)=>{if(url.includes('/contents/')){if(init.method==='GET')return journal?response(200,{sha:'b'.repeat(40),content:Buffer.from(JSON.stringify(journal)).toString('base64')}):response(404,null);if(failJournal){failJournal=false;return response(503,{})}journal=plan;return response(201,{content:{sha:'b'.repeat(40)},commit:{sha:'c'.repeat(40)}});}if(url.includes(listingPath)&&init.method==='GET')return response(200,listingResponse(posts,plan));if(init.method==='POST'){posts++;return response(201,{id:posts});}return response(200,{});};const transport=createGitHubActionsTransport({tokenProvider:()=> 'token',fetchImpl,issueNumber:115});await assert.rejects(()=>transport.publish(plan));assert.equal((await transport.publish(plan)).published,true);assert.equal(posts,1);}
test('comment replay reconciles hidden marker after journal write failure',async()=>{const plan=planCommentPublication({request,body:'comment',at});await replayCase(plan,'/issues/115/comments',(_posts,p)=>_posts?[{body:`comment\n\n<!-- audit-direct:${p.publicationId} -->`}]:[]);});
test('status replay reconciles exact context/state/description after journal failure',async()=>{const plan=planStatusPublication({request,state:'error',description:'Unavailable',context:'curveyield/direct',at});await replayCase(plan,'/statuses?per_page=100',(posts,p)=>posts?[{context:p.context,state:p.state,description:p.description}]:[]);});
test('check replay reconciles external id and conclusion after journal failure',async()=>{const plan=planCheckPublication({request,name:'CurveYield Audit',summary:'summary',conclusion:'neutral',at});await replayCase(plan,'/check-runs?',(posts,p)=>({check_runs:posts?[{external_id:p.idempotencyKey,conclusion:p.conclusion}]:[]}));});
test('workflow host reads only derived ledger paths',async()=>{const source=await readFile(new URL('../apps/audit-github-direct-cli/src/workflow-host.mjs',import.meta.url),'utf8');assert.match(source,/manifests\/\$\{request\.jobId\}-admission\.json/);assert.match(source,/createGitHubActionsLedgerSnapshotReader/);assert.doesNotMatch(source,/callerPath|inputPath/);});
