import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryAuditStore } from './audit-phase7-in-memory-store-v1.mjs';
import { checkpointObjectKey, forkRestoreManifestKey, forkTombstoneKey, sha256Hex } from '../packages/audit-fork-protocol/src/index.mjs';
async function forks(){ try { return await import('../packages/audit-forks/src/index.mjs'); } catch(cause) { assert.fail(`Phase 7 storage module unavailable: ${cause.code}`); } }
const forkId='fork_'+'4'.repeat(32), tenantId='ten_'+'1'.repeat(32), attemptId='att_'+'5'.repeat(32);
const readInput={forkId,tenantId,attemptId};
function request(){ return {schemaVersion:'fork-request-v1',tenantId,workspaceId:'ws_'+'2'.repeat(32),campaignId:'cmp_'+'3'.repeat(32),forkId,attemptId,profileId:'free-development-v1',policyVersion:'fork-policy-v1',requesterId:'usr',scopes:['audit:read','audit:submit'],chainId:1,blockNumber:21000000,blockHash:'0x'+'a'.repeat(64),adapterKind:'mock',executionGate:'trusted_mock',createdAt:'2026-08-01T00:00:00.000Z',idempotencyKey:'create'}; }
async function manifest(index, bytes){ const checkpointId='snap_'+index.toString(16).padStart(32,'0'); return {schemaVersion:'fork-checkpoint-manifest-v1',checkpointId,forkId,tenantId,attemptId,chainId:1,blockNumber:21000000+index,blockHash:'0x'+'a'.repeat(64),objectKey:checkpointObjectKey(forkId,checkpointId),sha256:await sha256Hex(bytes),bytes:bytes.byteLength,contentType:'application/octet-stream',opaque:true,encryption:{mode:'client-managed',keyReference:'opaque'},createdAt:'2026-08-01T00:00:00.000Z',expiresAt:'2026-08-02T00:00:00.000Z'}; }
test('stores one opaque checkpoint object plus manifest and enforces eight-checkpoint cap',async()=>{ const f=await forks(); const service=new f.ForkService(new InMemoryAuditStore()); await service.createFork(request()); for(let i=1;i<=8;i++){ const bytes=new Uint8Array([i]); await service.publishCheckpoint({manifest:await manifest(i,bytes),bytes}); } const bytes=new Uint8Array([9]); const ninth=await manifest(9,bytes); await assert.rejects(()=>service.publishCheckpoint({manifest:ninth,bytes}),{code:'checkpoint_quota_exceeded'}); });
test('export references checkpoint object without copying bytes and deletion leaves tombstone',async()=>{ const f=await forks(); const store=new InMemoryAuditStore(); const service=new f.ForkService(store); await service.createFork(request()); const bytes=new Uint8Array([1,2,3]); const cp=await manifest(1,bytes); await service.publishCheckpoint({manifest:cp,bytes}); const exp=await service.exportCheckpoint({schemaVersion:'fork-export-manifest-v1',exportId:'exp_'+'7'.repeat(32),forkId,tenantId,checkpointId:cp.checkpointId,sourceObjectKey:cp.objectKey,sourceSha256:cp.sha256,createdAt:'2026-08-01T01:00:00.000Z',expiresAt:'2026-08-08T01:00:00.000Z'}); assert.equal(exp.sourceObjectKey,cp.objectKey); assert.equal(service.operationTrace().some((entry)=>entry.method==='copy'),false); await service.deleteFork({forkId,tenantId,attemptId,occurredAt:'2026-08-01T02:00:00.000Z',reason:'user-request'}); assert.equal(await store.head(cp.objectKey),null); assert.ok(await store.head(forkTombstoneKey(forkId))); assert.equal((await service.readFork(readInput)).state,'deleted'); });
test('restore persists an immutable manifest that references the existing checkpoint object',async()=>{ const f=await forks(); const store=new InMemoryAuditStore(); const service=new f.ForkService(store); await service.createFork(request()); const bytes=new Uint8Array([4,5,6]); const cp=await manifest(1,bytes); await service.publishCheckpoint({manifest:cp,bytes}); const restore={schemaVersion:'fork-restore-manifest-v1',restoreId:'rst_'+'8'.repeat(32),forkId,tenantId,attemptId,checkpointId:cp.checkpointId,sourceObjectKey:cp.objectKey,sourceSha256:cp.sha256,requestedAt:'2026-08-01T01:00:00.000Z'}; const restored=await service.restoreCheckpoint(restore); assert.equal(restored.sourceSha256,cp.sha256); assert.ok(await store.head(forkRestoreManifestKey(forkId,restore.restoreId))); });
test('checkpoint rejects unauthorized identity, chain drift, size mismatch, and digest mismatch before publication',async()=>{ const f=await forks(); const store=new InMemoryAuditStore(); const service=new f.ForkService(store); await service.createFork(request()); const bytes=new Uint8Array([9,8,7]); const valid=await manifest(1,bytes); await assert.rejects(()=>service.publishCheckpoint({manifest:{...valid,tenantId:'ten_'+'9'.repeat(32)},bytes}),{code:'unauthorized_tenant'}); await assert.rejects(()=>service.publishCheckpoint({manifest:{...valid,chainId:10},bytes}),{code:'chain_block_drift'}); await assert.rejects(()=>service.publishCheckpoint({manifest:{...valid,bytes:2},bytes}),{code:'size_mismatch'}); await assert.rejects(()=>service.publishCheckpoint({manifest:{...valid,sha256:'0'.repeat(64)},bytes}),{code:'digest_mismatch'}); assert.equal(await store.head(valid.objectKey),null); });
test('checkpoint and export traces include durable transient-state events and indexes',async()=>{ const f=await forks(); const service=new f.ForkService(new InMemoryAuditStore()); await service.createFork(request()); service.clearOperationTrace(); const bytes=new Uint8Array([1]); const cp=await manifest(1,bytes); await service.publishCheckpoint({manifest:cp,bytes}); const checkpointCounts=service.operationTrace().reduce((r,e)=>(r[e.billingClass]=(r[e.billingClass]??0)+1,r),{}); assert.deepEqual(checkpointCounts,{'class-b':9,'class-a':9}); service.clearOperationTrace(); await service.exportCheckpoint({schemaVersion:'fork-export-manifest-v1',exportId:'exp_'+'6'.repeat(32),forkId,tenantId,checkpointId:cp.checkpointId,sourceObjectKey:cp.objectKey,sourceSha256:cp.sha256,createdAt:'2026-08-01T01:00:00.000Z',expiresAt:'2026-08-08T01:00:00.000Z'}); const exportCounts=service.operationTrace().reduce((r,e)=>(r[e.billingClass]=(r[e.billingClass]??0)+1,r),{}); assert.deepEqual(exportCounts,{'class-b':10,'class-a':8}); });
