import test from 'node:test';
import assert from 'node:assert/strict';
import {createForkReportProjection,createCheckpointReportProjection,createExportReportProjection,createDeleteReportProjection} from '../packages/audit-fork-reporting/src/index.mjs';
import {createCampaignReportProjection,createMergeReportProjection,createRelationSummary,createProvenanceReportProjection,createHiddenReportProjection} from '../packages/audit-clean-room-reporting/src/index.mjs';
import {createTerminalCampaignManifest} from '../packages/audit-clean-room-campaigns/src/index.mjs';
import {createDuplicateRelation,createConflictRelation,createMergeRequest,createMergeManifest} from '../packages/audit-controlled-merge/src/index.mjs';
import {createProvenanceIndex} from '../packages/audit-provenance/src/index.mjs';

const D=`sha256:${'1'.repeat(64)}`,E=`sha256:${'2'.repeat(64)}`,F=`sha256:${'3'.repeat(64)}`,RAW='1'.repeat(64);
const TEN=`ten_${'a'.repeat(32)}`,FORK=`fork_${'b'.repeat(32)}`,ATT=`att_${'c'.repeat(32)}`,SNAP=`snap_${'d'.repeat(32)}`,EXP=`exp_${'e'.repeat(32)}`;
const AT='2026-08-02T10:00:00.000Z',DAY='2026-08-03T10:00:00.000Z',WEEK='2026-08-09T10:00:00.000Z';
function state(overrides={}){return {schemaVersion:'fork-state-v1',forkId:FORK,tenantId:TEN,attemptId:ATT,requestDigest:RAW,state:'ready',version:2,executionGate:'trusted_mock',adapterKind:'mock',chainId:1,blockNumber:100,blockHash:null,createdAt:AT,updatedAt:AT,lastTransitionId:'tr_ready_test',lastFromState:'requested',...overrides};}
function checkpoint(overrides={}){return {schemaVersion:'fork-checkpoint-manifest-v1',checkpointId:SNAP,forkId:FORK,tenantId:TEN,attemptId:ATT,chainId:1,blockNumber:100,blockHash:null,objectKey:`forks/${FORK}/checkpoints/${SNAP}.bin`,sha256:RAW,bytes:1000,contentType:'application/octet-stream',opaque:true,encryption:{mode:'none',keyReference:'none'},createdAt:AT,expiresAt:DAY,...overrides};}
function exported(overrides={}){return {schemaVersion:'fork-export-manifest-v1',exportId:EXP,forkId:FORK,tenantId:TEN,checkpointId:SNAP,sourceObjectKey:`forks/${FORK}/checkpoints/${SNAP}.bin`,sourceSha256:RAW,createdAt:AT,expiresAt:WEEK,...overrides};}
function campaign(campaignId='campaign-a'){return createTerminalCampaignManifest({tenantId:'tenant-a',workspaceId:'workspace-a',campaignId,workspaceSourceDigest:D,baseArtifactDigest:E,terminalState:'completed',completionKind:'success',partialEvidence:false,truncated:false,policyId:'policy-a',profileVersions:[],layerRefs:[],jobRefs:[],attemptRefs:[],evidenceRefs:[],reportRefs:[],findings:[],completedAt:AT});}
function mergeManifest(){const a=campaign('campaign-a'),b=campaign('campaign-b');const request=createMergeRequest({terminalManifests:[a,b],policyId:'policy-a',requestedBy:'requester-a',requestedAt:AT,idempotencyKey:'merge-idem-a',expectedCurrentEtag:D});return createMergeManifest({mergeRequest:request,finalState:'completed',terminalManifestDigests:[a.manifestDigest,b.manifestDigest],duplicateMapDigest:D,conflictMapDigest:E,provenanceIndexDigest:F,mergedReportRefs:[],policyId:'policy-a',operationSummary:{classA:4,classB:4,retainedBytes:2_000_000,retentionDays:90,variant:'typical'},publishedAt:AT});}
function finding(campaignId,findingId,overrides={}){return {findingId,campaignId,identityKey:'identity-a',severity:'high',status:'open',remediation:'fix-a',location:'file-a',materialDigest:D,evidenceRefs:[],...overrides};}

test('fork report validates state and recursively freezes output',()=>{const report=createForkReportProjection({state:state(),requestedBy:'requester-a',reportedAt:AT});assert.equal(report.status,'ready');assert.equal(report.requestDigest,`sha256:${RAW}`);assert.ok(Object.isFrozen(report));});
test('fork report accepts only the transport etag as a stripped field',()=>{const report=createForkReportProjection({state:{...state(),etag:D},requestedBy:'requester-a',reportedAt:AT});assert.equal(report.status,'ready');});
test('fork report rejects hostile accessors without invoking them',()=>{let invoked=0;const input=state();Object.defineProperty(input,'state',{enumerable:true,get(){invoked++;throw new Error('secret');}});assert.throws(()=>createForkReportProjection({state:input,requestedBy:'requester-a',reportedAt:AT}),e=>['accessor_field','hostile_reflection'].includes(e.code));assert.equal(invoked,0);});
test('checkpoint report validates exact manifest and retention',()=>{const report=createCheckpointReportProjection({manifest:checkpoint(),reportedAt:AT});assert.equal(report.attemptId,ATT);assert.equal(report.retentionSeconds,86400);assert.equal(report.opaque,true);});
test('checkpoint report rejects invalid content type',()=>{assert.throws(()=>createCheckpointReportProjection({manifest:checkpoint({contentType:'text/html'}),reportedAt:AT}),e=>['invalid_content_type','invalid_manifest'].includes(e.code));});
test('export report validates source reference and does not claim byte copying',()=>{const report=createExportReportProjection({manifest:exported(),reportedAt:AT});assert.equal(report.copiesBytes,false);assert.equal(report.retentionSeconds,604800);});
test('delete report validates state tombstone identity congruence',()=>{const deleted=state({state:'deleted',version:4,lastTransitionId:'tr_delete_test',lastFromState:'deleting',deletedAt:AT,tombstone:true});const tombstone={schemaVersion:'fork-tombstone-v1',forkId:FORK,tenantId:TEN,attemptId:ATT,reason:'cleanup',deletedAt:AT,requestDigest:RAW};const report=createDeleteReportProjection({state:deleted,tombstone,reportedAt:AT});assert.equal(report.terminal,true);});
test('delete report rejects attempt substitution',()=>{const deleted=state({state:'deleted',version:4,lastTransitionId:'tr_delete_test',lastFromState:'deleting',deletedAt:AT,tombstone:true});const tombstone={schemaVersion:'fork-tombstone-v1',forkId:FORK,tenantId:TEN,attemptId:`att_${'d'.repeat(32)}`,reason:'cleanup',deletedAt:AT,requestDigest:RAW};assert.throws(()=>createDeleteReportProjection({state:deleted,tombstone,reportedAt:AT}),e=>e.code==='deletion_identity_mismatch');});
test('campaign report derives complete and inventory from validated manifest',()=>{const report=createCampaignReportProjection({manifest:campaign(),reportedAt:AT});assert.equal(report.complete,true);assert.equal(report.inventorySummary.findingCount,0);assert.ok(Object.isFrozen(report.inventorySummary));});
test('campaign report rejects recomputed-looking tampered digest',()=>{const m={...campaign(),manifestDigest:F};assert.throws(()=>createCampaignReportProjection({manifest:m,reportedAt:AT}),e=>e.code==='digest_mismatch');});
test('merge report validates manifest membership and bounded operation summary',()=>{const report=createMergeReportProjection({manifest:mergeManifest(),reportedAt:AT});assert.equal(report.sourceCampaignCount,2);assert.equal(report.operationSummary.classA,4);assert.ok(Object.isFrozen(report.operationSummary));});
test('merge report rejects tampered operation summary even with original digest',()=>{const m=mergeManifest();assert.throws(()=>createMergeReportProjection({manifest:{...m,operationSummary:{...m.operationSummary,classA:1001}},reportedAt:AT}),e=>['invalid_integer','digest_mismatch'].includes(e.code));});
test('fully visible duplicate relation is counted',()=>{const relation=createDuplicateRelation([finding('campaign-a','finding-a'),finding('campaign-b','finding-b')]);const summary=createRelationSummary({duplicateRelations:[relation],conflictRelations:[],visibleCampaignIds:['campaign-a','campaign-b']});assert.deepEqual(summary,{schemaVersion:'audit-phase9-relation-summary-v2',duplicateGroups:1,conflictGroups:0,visibleMembers:2});});
test('partially hidden duplicate relation is omitted without a presence signal',()=>{const relation=createDuplicateRelation([finding('campaign-a','finding-a'),finding('campaign-hidden','finding-b')]);const summary=createRelationSummary({duplicateRelations:[relation],conflictRelations:[],visibleCampaignIds:['campaign-a']});assert.deepEqual(summary,{schemaVersion:'audit-phase9-relation-summary-v2',duplicateGroups:0,conflictGroups:0,visibleMembers:0});});
test('fully visible conflict relation is counted after semantic validation',()=>{const relation=createConflictRelation([finding('campaign-a','finding-a'),finding('campaign-b','finding-b',{severity:'critical',materialDigest:E})]);const summary=createRelationSummary({duplicateRelations:[],conflictRelations:[relation],visibleCampaignIds:['campaign-a','campaign-b']});assert.equal(summary.conflictGroups,1);assert.equal(summary.visibleMembers,2);});
test('tampered relation digest is rejected',()=>{const relation=createDuplicateRelation([finding('campaign-a','finding-a'),finding('campaign-b','finding-b')]);assert.throws(()=>createRelationSummary({duplicateRelations:[{...relation,relationDigest:F}],conflictRelations:[],visibleCampaignIds:['campaign-a','campaign-b']}),e=>e.code==='digest_mismatch');});
test('visible provenance identity is invariant to hidden nodes',()=>{const common={tenantId:'tenant-a',workspaceId:'workspace-a',mergeId:'merge-a',createdAt:AT,edges:[]};const visible={nodeId:'node-visible',type:'finding',tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-a',digest:D,sourceRef:null};const hidden={nodeId:'node-hidden',type:'finding',tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-hidden',digest:E,sourceRef:null};const a=createProvenanceReportProjection({index:createProvenanceIndex({...common,nodes:[visible]}),nodeId:'node-visible',visibleCampaignIds:['campaign-a'],reportedAt:AT});const b=createProvenanceReportProjection({index:createProvenanceIndex({...common,nodes:[visible,hidden]}),nodeId:'node-visible',visibleCampaignIds:['campaign-a'],reportedAt:AT});assert.equal(a.reportDigest,b.reportDigest);assert.equal(a.indexDigest,b.indexDigest);});
test('hidden and absent provenance targets return byte-identical projection',()=>{const index=createProvenanceIndex({tenantId:'tenant-a',workspaceId:'workspace-a',mergeId:'merge-a',createdAt:AT,nodes:[{nodeId:'node-hidden',type:'finding',tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-hidden',digest:D,sourceRef:null}],edges:[]});const hidden=createProvenanceReportProjection({index,nodeId:'node-hidden',visibleCampaignIds:['campaign-a'],reportedAt:AT});const absent=createProvenanceReportProjection({index,nodeId:'node-absent',visibleCampaignIds:['campaign-a'],reportedAt:AT});assert.deepEqual(hidden,absent);assert.deepEqual(hidden,createHiddenReportProjection());assert.equal(Object.hasOwn(hidden,'total'),false);});
test('provenance report rejects tampered index digest',()=>{const index=createProvenanceIndex({tenantId:'tenant-a',workspaceId:'workspace-a',mergeId:'merge-a',createdAt:AT,nodes:[],edges:[]});assert.throws(()=>createProvenanceReportProjection({index:{...index,indexDigest:F},nodeId:'node-a',visibleCampaignIds:[],reportedAt:AT}),e=>e.code==='digest_mismatch');});
test('hidden projection is recursively frozen and count invariant',()=>{const hidden=createHiddenReportProjection();assert.ok(Object.isFrozen(hidden));assert.ok(Object.isFrozen(hidden.operationBudget));assert.equal(Object.hasOwn(hidden,'total'),false);});
