import test from 'node:test';
import assert from 'node:assert/strict';
import {
  SAFE_CAPABILITIES, ROUND4_INTAKE_SLOTS,
  createPublicInterfaceLock, validatePublicInterfaceLock, assertPublicInterfaceCompatibility,
  createComponentManifest, validateComponentManifest,
  validateSharedFileUnion, createReleaseIntakePlan,
  createReleaseIntegrationManifest, validateReleaseIntegrationManifest,
  canonicalJson
} from '../packages/audit-release-integration/src/index.mjs';
const s=c=>c.repeat(40);
const report=(issue=114,comment=5156779012)=>({issueNumber:issue,commentId:comment,url:`https://github.com/CurveYield/contract-automation/issues/${issue}#issuecomment-${comment}`});
const cap=(overrides={})=>({...SAFE_CAPABILITIES,...overrides});
function lock(id='a',overrides={}){return createPublicInterfaceLock({componentId:id,schemaVersion:`${id}-public-v1`,entrypoints:[`packages/${id}/src/index.mjs`],exports:[`create${id.toUpperCase()}`],storagePrefixes:[`${id}/`],lifecycleOutcomes:['completed'],capabilities:cap(),...overrides});}
function op(path,source='b',destination=source,kind='exact',repairId=null){return{path,sourceBlobSha:source===null?null:s(source),destinationBlobSha:destination===null?null:s(destination),adaptationKind:kind,repairId};}
function component(id='a',paths=[op(`packages/${id}/src/index.mjs`)],overrides={}){return createComponentManifest({componentId:id,issueNumber:114,branch:`audit-round4/${id}-v1`,finalSha:s('a'),status:'completed',recommendation:paths.some(x=>['repaired','deleted'].includes(x.adaptationKind))?'ACCEPT WITH REPAIR':'ACCEPT',report:report(),paths,publicInterface:lock(id),...overrides});}

test('interface permutations are canonical and immutable',()=>{const a=createPublicInterfaceLock({componentId:'a',schemaVersion:'a-public-v1',entrypoints:['packages/a/src/z.mjs','packages/a/src/a.mjs'],exports:['z','a'],storagePrefixes:['z/','a/'],lifecycleOutcomes:['failed','completed'],capabilities:cap()});const b=createPublicInterfaceLock({componentId:'a',schemaVersion:'a-public-v1',entrypoints:['packages/a/src/a.mjs','packages/a/src/z.mjs'],exports:['a','z'],storagePrefixes:['a/','z/'],lifecycleOutcomes:['completed','failed'],capabilities:cap()});assert.deepEqual(a,b);assert.equal(Object.isFrozen(a.entrypoints),true);});
test('interface drift is rejected',()=>{const a=lock();const b=createPublicInterfaceLock({componentId:'a',schemaVersion:'a-public-v1',entrypoints:['packages/a/src/other.mjs'],exports:['createA'],storagePrefixes:['a/'],lifecycleOutcomes:['completed'],capabilities:cap()});assert.throws(()=>assertPublicInterfaceCompatibility(a,b),{code:'public_interface_drift'});});
test('capability broadening is rejected',()=>assert.throws(()=>createPublicInterfaceLock({componentId:'a',schemaVersion:'a-public-v1',entrypoints:['packages/a/src/index.mjs'],exports:['createA'],storagePrefixes:['a/'],lifecycleOutcomes:['completed'],capabilities:cap({networkEnabled:true})}),{code:'capability_broadening'}));
test('accessors are rejected without invocation',()=>{let invoked=0;const hostile={};Object.defineProperty(hostile,'componentId',{enumerable:true,get(){invoked++;throw new Error('boom')}});assert.throws(()=>createComponentManifest(hostile),{code:'accessor_field'});assert.equal(invoked,0);});
test('hidden symbol custom prototype cycle and sparse arrays are rejected',()=>{const hidden={componentId:'a'};Object.defineProperty(hidden,'secret',{value:'x',enumerable:false});assert.throws(()=>createComponentManifest(hidden),{code:'hidden_field'});assert.throws(()=>createComponentManifest({[Symbol('x')]:1}),{code:'symbol_field'});assert.throws(()=>createComponentManifest(Object.create({})),{code:'invalid_object'});const cyclic={};cyclic.self=cyclic;assert.throws(()=>createComponentManifest(cyclic),{code:'cyclic_value'});const sparse=[];sparse.length=1;assert.throws(()=>createComponentManifest({componentId:'a',issueNumber:114,branch:'a',finalSha:s('a'),status:'completed',recommendation:'ACCEPT',report:report(),paths:sparse,publicInterface:lock()}),{code:'sparse_array'});});
test('component builder and validator are permutation invariant',()=>{const paths=[op('packages/a/src/z.mjs'),op('packages/a/src/index.mjs')];const first=component('a',paths);const second=createComponentManifest({componentId:'a',issueNumber:114,branch:'audit-round4/a-v1',finalSha:s('a'),status:'completed',recommendation:'ACCEPT',report:report(),paths:[...paths].reverse(),publicInterface:lock('a')});assert.deepEqual(first,second);assert.deepEqual(validateComponentManifest(first),first);});
test('adaptation truth table rejects source/destination drift',()=>{assert.throws(()=>component('a',[op('packages/a/src/index.mjs','b','c','exact')]),{code:'invalid_adaptation'});assert.throws(()=>component('a',[op('packages/a/src/index.mjs',null,'c','repaired','r')]),{code:'invalid_adaptation'});assert.throws(()=>component('a',[op('packages/a/src/index.mjs','b','c','added','r')]),{code:'invalid_adaptation'});assert.throws(()=>component('a',[op('packages/a/src/index.mjs','b','c','deleted','r')]),{code:'invalid_adaptation'});});
test('nested ownership and protected paths are rejected',()=>{const a=component('a',[op('packages/a/src')]);const b=component('b',[op('packages/a/src/index.mjs','b','c','repaired','overlap-b')]);assert.throws(()=>createReleaseIntakePlan({baseSha:s('0'),candidates:[a,b],protectedPaths:[],sharedUnions:[]}),{code:'path_overlap'});assert.throws(()=>createReleaseIntakePlan({baseSha:s('0'),candidates:[a],protectedPaths:['packages/a/src/index.mjs'],sharedUnions:[]}),{code:'protected_path'});});
test('shared unions bind ownership base and destination blobs',()=>{const a=component('a',[op('package.json','1','2','repaired','r-a')]);const b=component('b',[op('package.json','1','3','repaired','r-b')]);const base={schemaVersion:'audit-shared-file-union-v1',path:'package.json',baseBlobSha:s('1'),inputs:[{componentId:'a',blobSha:s('2'),fields:['exports.a']},{componentId:'b',blobSha:s('3'),fields:['scripts.b']}],outputBlobSha:s('4'),strategy:'field-owned-v1'};assert.equal(createReleaseIntakePlan({baseSha:s('0'),candidates:[a,b],protectedPaths:[],sharedUnions:[base]}).sharedUnions.length,1);assert.throws(()=>createReleaseIntakePlan({baseSha:s('0'),candidates:[a,b],protectedPaths:[],sharedUnions:[{...base,baseBlobSha:s('9')}]}),{code:'union_base_mismatch'});const bad={...base,inputs:[{componentId:'a',blobSha:s('8'),fields:['exports.a']},{componentId:'b',blobSha:s('3'),fields:['scripts.b']}]};assert.throws(()=>createReleaseIntakePlan({baseSha:s('0'),candidates:[a,b],protectedPaths:[],sharedUnions:[bad]}),{code:'union_blob_mismatch'});});
test('union fields reject parent-child overlap',()=>assert.throws(()=>validateSharedFileUnion({schemaVersion:'audit-shared-file-union-v1',path:'package.json',baseBlobSha:s('1'),inputs:[{componentId:'a',blobSha:s('2'),fields:['exports']},{componentId:'b',blobSha:s('3'),fields:['exports.b']}],outputBlobSha:s('4'),strategy:'field-owned-v1'}),{code:'union_field_overlap'}));
test('release manifest validates round-trip and digest/capability tampering',()=>{const manifest=createReleaseIntegrationManifest({baseSha:s('0'),components:[component()],protectedBlobs:[{path:'packages/runner/src/run-job.mjs',blobSha:s('1')}],sharedUnions:[],staleInputs:['stale-a'],round4Slots:ROUND4_INTAKE_SLOTS});assert.deepEqual(validateReleaseIntegrationManifest(manifest),manifest);const digest=structuredClone(manifest);digest.releaseDigest=s('9');assert.throws(()=>validateReleaseIntegrationManifest(digest),{code:'digest_mismatch'});const capability=structuredClone(manifest);capability.capabilities.networkEnabled=true;assert.throws(()=>validateReleaseIntegrationManifest(capability),{code:'capability_drift'});});
test('round4 intake slots are exact',()=>{const changed=structuredClone(ROUND4_INTAKE_SLOTS);changed[0].issueNumber=999;assert.throws(()=>createReleaseIntegrationManifest({baseSha:s('0'),components:[component()],protectedBlobs:[],sharedUnions:[],staleInputs:[],round4Slots:changed}),{code:'round4_slot_mismatch'});});
test('release intake is candidate-order independent',()=>{const a=component('a'),b=component('b');const left=createReleaseIntakePlan({baseSha:s('0'),candidates:[a,b],protectedPaths:[],sharedUnions:[]});const right=createReleaseIntakePlan({baseSha:s('0'),candidates:[b,a],protectedPaths:[],sharedUnions:[]});assert.equal(canonicalJson(left),canonicalJson(right));});
