import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as service from '../packages/audit-phase78-service/src/index.mjs';
import {planImmutablePublication,planScopedPublicationRecovery} from '../packages/audit-phase78-publication/src/index.mjs';
import {createProvenanceReportProjection,createHiddenReportProjection} from '../packages/audit-clean-room-reporting/src/index.mjs';
import {createProvenanceIndex} from '../packages/audit-provenance/src/index.mjs';

const D=`sha256:${'1'.repeat(64)}`,E=`sha256:${'2'.repeat(64)}`,F=`sha256:${'3'.repeat(64)}`;
const AT='2026-08-02T12:00:00.000Z';
const fixture=JSON.parse(readFileSync(new URL('./fixtures/audit-round4/worker1/multi-tenant-scenarios-v1.json',import.meta.url),'utf8'));
function request({tenant='tenant-a',workspace='workspace-a',campaign='campaign-a',fork='fork-a',attempt='attempt-a',operation='fork.checkpoint',id='idem-a',payload={checkpointId:'checkpoint-a',manifestDigest:E},scopes=['audit:submit'],expectedVersion=4,expectedEtag=D}={}){return service.createServiceRequest({operation,tenantId:tenant,workspaceId:workspace,campaignId:campaign,forkId:fork,attemptId:attempt,mergeId:null,requesterId:'requester-a',scopes,idempotencyKey:id,expectedVersion,expectedEtag,requestedAt:AT,payload});}
function current(req,state='ready'){return {version:4,etag:D,state,tenantId:req.tenantId,forkId:req.forkId,attemptId:req.attemptId};}
function pageOptions(req,overrides={}){return {tenantId:req.tenantId,workspaceId:req.workspaceId,campaignId:req.campaignId,forkId:req.forkId,attemptId:req.attemptId,mergeId:null,resourceKind:'checkpoint',indexDigest:D,viewDigest:E,pageSize:1,cursor:null,...overrides};}
const items=[{id:'checkpoint-a',createdAt:AT,digest:D},{id:'checkpoint-b',createdAt:'2026-08-02T12:01:00.000Z',digest:E}];
function steps(){return [{stepId:'immutable-a',kind:'immutable',phase:'immutable',digest:D},{stepId:'index-a',kind:'index',phase:'index-cas',digest:E},{stepId:'pointer-a',kind:'pointer',phase:'pointer-last',digest:F}];}

test('scenario fixture is exact and complete',()=>{assert.equal(fixture.schemaVersion,'audit-round4-worker1-multi-tenant-scenarios-v1');assert.equal(fixture.scenarios.length,fixture.scenarioCount);assert.equal(new Set(fixture.scenarios.map(x=>x.id)).size,fixture.scenarioCount);});
test('tenant and attempt identities are part of request digests',()=>{const a=request({});const tenant=request({tenant:'tenant-b',workspace:'workspace-b',campaign:'campaign-b',fork:'fork-b',attempt:'attempt-b',id:'idem-b'});const attempt=request({attempt:'attempt-b',id:'idem-c'});assert.notEqual(a.requestDigest,tenant.requestDigest);assert.notEqual(a.requestDigest,attempt.requestDigest);});
test('same exact request is deterministic',()=>{assert.deepEqual(request({}),request({}));});
test('correct tenant attempt read is allowed',()=>{const req=request({operation:'fork.read',payload:{},scopes:['audit:read'],expectedVersion:null,expectedEtag:null});const result=service.authorizePhase78Operation(req,{forkState:{tenantId:req.tenantId,forkId:req.forkId,attemptId:req.attemptId}});assert.equal(result.allowed,true);});
test('cross-tenant and cross-attempt reads collapse to one hidden result',()=>{const req=request({operation:'fork.read',payload:{},scopes:['audit:read'],expectedVersion:null,expectedEtag:null});const absent=service.authorizePhase78Operation(req,{forkState:null});const tenant=service.authorizePhase78Operation(req,{forkState:{tenantId:'tenant-b',forkId:req.forkId,attemptId:req.attemptId}});const attempt=service.authorizePhase78Operation(req,{forkState:{tenantId:req.tenantId,forkId:req.forkId,attemptId:'attempt-b'}});assert.deepEqual(tenant,absent);assert.deepEqual(attempt,absent);});
test('checkpoint export restore and delete plans retain exact attempt scope',()=>{for(const [operation,payload] of [['fork.checkpoint',{checkpointId:'checkpoint-a',manifestDigest:E}],['fork.export',{checkpointId:'checkpoint-a',exportId:'export-a'}],['fork.restore',{checkpointId:'checkpoint-a',restoreId:'restore-a',manifestDigest:E}],['fork.delete',{reason:'cleanup'}]]){const req=request({operation,payload,id:`idem-${operation}`});const plan=service.planPhase78Operation({request:req,authorization:{allowed:true},current:current(req)});assert.equal(plan.attemptId,req.attemptId);assert.equal(plan.executionEnabled,false);assert.equal(plan.terminalProtection,true);}});
test('cross-attempt cursor reuse is rejected',()=>{const a=request({}),b=request({attempt:'attempt-b',id:'idem-b'});const first=service.paginateDeterministically(items,pageOptions(a));assert.throws(()=>service.paginateDeterministically(items,pageOptions(b,{cursor:first.nextCursor})),e=>e.code==='cursor_scope_mismatch');});
test('visible-view drift invalidates cursor without hidden totals',()=>{const req=request({});const first=service.paginateDeterministically(items,pageOptions(req));assert.equal(Object.hasOwn(first,'total'),false);assert.throws(()=>service.paginateDeterministically(items,pageOptions(req,{viewDigest:F,cursor:first.nextCursor})),e=>e.code==='stale_cursor');});
test('publication keys are isolated by tenant and attempt',()=>{const a=request({}),attempt=request({attempt:'attempt-b',id:'idem-b'}),tenant=request({tenant:'tenant-b',workspace:'workspace-b',campaign:'campaign-b',fork:'fork-b',attempt:'attempt-b',id:'idem-c'});const key=req=>planImmutablePublication({request:req,records:[{kind:'checkpoint',id:'checkpoint-a',digest:E,bytes:100,retentionDays:1}]}).operations[0].key;assert.equal(new Set([key(a),key(attempt),key(tenant)]).size,3);});
test('request-bound response rejects tenant substitution after valid recomputation',()=>{const req=request({});const response=service.createServiceResponse({request:req,status:'accepted',resourceId:'checkpoint-a',version:5,etag:E,body:{ok:true},completedAt:AT});const core={...response,tenantId:'tenant-b'};delete core.responseDigest;const tampered={...core,responseDigest:service.sha256(core)};assert.throws(()=>service.validateServiceResponseForRequest(tampered,req),e=>e.code==='response_identity_mismatch');});
test('typed replay converges immutable then index then pointer',()=>{const req=request({});const one=planScopedPublicationRecovery({request:req,plannedSteps:steps(),completedSteps:[],failedStep:'immutable-a'});const two=planScopedPublicationRecovery({request:req,plannedSteps:steps(),completedSteps:[steps()[0]],failedStep:'index-a'});const three=planScopedPublicationRecovery({request:req,plannedSteps:steps(),completedSteps:[steps()[0],steps()[1]],failedStep:'pointer-a'});assert.deepEqual(one.remainingSteps.map(x=>x.stepId),['immutable-a','index-a','pointer-a']);assert.deepEqual(two.remainingSteps.map(x=>x.stepId),['index-a','pointer-a']);assert.deepEqual(three.remainingSteps.map(x=>x.stepId),['pointer-a']);});
test('conflicting replay evidence is rejected',()=>{const req=request({});assert.throws(()=>planScopedPublicationRecovery({request:req,plannedSteps:steps(),completedSteps:[{...steps()[0],digest:F}],failedStep:'immutable-a'}),e=>e.code==='recovery_conflict');});
test('pointer-before-index replay is rejected',()=>{const req=request({});assert.throws(()=>planScopedPublicationRecovery({request:req,plannedSteps:steps(),completedSteps:[steps()[2]],failedStep:'pointer-a'}),e=>e.code==='pointer_order_conflict');});
test('cancelled and failed forks cannot plan writes',()=>{for(const state of ['cancelled','failed','deleted']){const req=request({});assert.throws(()=>service.planPhase78Operation({request:req,authorization:{allowed:true},current:current(req,state)}),e=>e.code==='terminal_state');}});
test('hidden and absent provenance remain byte-identical',()=>{const node={nodeId:'node-hidden',type:'finding',tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-hidden',digest:D,sourceRef:null};const index=createProvenanceIndex({tenantId:'tenant-a',workspaceId:'workspace-a',mergeId:'merge-a',nodes:[node],edges:[],createdAt:AT});const hidden=createProvenanceReportProjection({index,nodeId:'node-hidden',visibleCampaignIds:['campaign-a'],reportedAt:AT});const absent=createProvenanceReportProjection({index,nodeId:'node-absent',visibleCampaignIds:['campaign-a'],reportedAt:AT});assert.deepEqual(hidden,absent);assert.deepEqual(hidden,createHiddenReportProjection());});
test('provider error revoked proxy is normalized without leakage',()=>{const {proxy,revoke}=Proxy.revocable({code:'checkpoint_not_found'},{});revoke();const result=service.normalizePhase78ServiceError(proxy,{requestId:'svc-req-a',operation:'fork.read',at:AT});assert.equal(result.code,'internal_error');assert.equal(result.message,'Request failed');});
test('request accessors are rejected without invocation',()=>{let invoked=0;const input={operation:'fork.read',tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-a',forkId:'fork-a',attemptId:'attempt-a',mergeId:null,requesterId:'requester-a',scopes:['audit:read'],idempotencyKey:'idem-a',expectedVersion:null,expectedEtag:null,requestedAt:AT,payload:{}};Object.defineProperty(input,'tenantId',{enumerable:true,get(){invoked++;throw new Error('secret');}});assert.throws(()=>service.createServiceRequest(input),e=>e.code==='accessor_field');assert.equal(invoked,0);});
test('sparse scope arrays are rejected',()=>{const scopes=new Array(2);scopes[0]='audit:read';assert.throws(()=>request({operation:'fork.read',payload:{},scopes,expectedVersion:null,expectedEtag:null}),e=>e.code==='sparse_array');});
test('cyclic response bodies are rejected before serialization',()=>{const req=request({});const body={};body.self=body;assert.throws(()=>service.createServiceResponse({request:req,status:'accepted',resourceId:'checkpoint-a',version:5,etag:E,body,completedAt:AT}),e=>e.code==='cycle');});
test('oversized response bodies are rejected by encoded-byte limits',()=>{const req=request({});assert.throws(()=>service.createServiceResponse({request:req,status:'accepted',resourceId:'checkpoint-a',version:5,etag:E,body:{text:'x'.repeat(service.LIMITS.bytes+1)},completedAt:AT}),e=>e.code==='encoded_bytes_exceeded');});
test('concurrent scope construction has no shared identity state',async()=>{const results=await Promise.all(Array.from({length:20},(_,i)=>Promise.resolve(request({tenant:`tenant-${i}`,workspace:`workspace-${i}`,campaign:`campaign-${i}`,fork:`fork-${i}`,attempt:`attempt-${i}`,id:`idem-${i}`}))));assert.equal(new Set(results.map(x=>x.requestDigest)).size,20);for(let i=0;i<results.length;i++)assert.equal(results[i].tenantId,`tenant-${i}`);});
