import test from 'node:test';
import assert from 'node:assert/strict';
import * as service from '../packages/audit-phase78-service/src/index.mjs';
import {planImmutablePublication,planMutablePointerPublication,validatePublicationPlan,planPublicationRecovery,planScopedPublicationRecovery,PUBLICATION_LIMITS} from '../packages/audit-phase78-publication/src/index.mjs';

const D=`sha256:${'1'.repeat(64)}`,E=`sha256:${'2'.repeat(64)}`,F=`sha256:${'3'.repeat(64)}`;
const AT='2026-08-02T11:30:00.000Z';
function request(overrides={}){return service.createServiceRequest({operation:'fork.checkpoint',tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-a',forkId:'fork-a',attemptId:'attempt-a',mergeId:null,requesterId:'requester-a',scopes:['audit:submit'],idempotencyKey:'idem-a',expectedVersion:4,expectedEtag:D,requestedAt:AT,payload:{checkpointId:'checkpoint-a',manifestDigest:E},...overrides});}
function record(overrides={}){return {kind:'checkpoint',id:'checkpoint-a',digest:E,bytes:100,retentionDays:1,...overrides};}
function steps(){return [{stepId:'immutable-a',kind:'immutable',phase:'immutable',digest:D},{stepId:'index-a',kind:'index',phase:'index-cas',digest:E},{stepId:'pointer-a',kind:'pointer',phase:'pointer-last',digest:F}];}

test('publication limits remain exact and frozen',()=>{assert.deepEqual(PUBLICATION_LIMITS,{records:64,bytes:20_000_000,retentionDays:90,checkpoints:8,exports:8,pageSize:100});assert.ok(Object.isFrozen(PUBLICATION_LIMITS));});
test('immutable publication binds exact campaign fork and attempt path',()=>{const plan=planImmutablePublication({request:request(),records:[record()]});assert.match(plan.operations[0].key,/tenants\/tenant-a\/workspaces\/workspace-a\/campaigns\/campaign-a\/forks\/fork-a\/attempts\/attempt-a\/checkpoint\/checkpoint-a-v2\.json$/);assert.equal(plan.scopeDigest,service.sha256({tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-a',forkId:'fork-a',attemptId:'attempt-a',mergeId:null}));});
test('different attempts produce different scoped keys and plan identities',()=>{const a=planImmutablePublication({request:request(),records:[record()]});const b=planImmutablePublication({request:request({attemptId:'attempt-b',idempotencyKey:'idem-b'}),records:[record()]});assert.notEqual(a.operations[0].key,b.operations[0].key);assert.notEqual(a.planDigest,b.planDigest);});
test('immutable publication sorts records deterministically',()=>{const a=planImmutablePublication({request:request(),records:[record({kind:'report',id:'report-b',digest:F}),record({kind:'checkpoint',id:'checkpoint-a'})]});const b=planImmutablePublication({request:request(),records:[record({kind:'checkpoint',id:'checkpoint-a'}),record({kind:'report',id:'report-b',digest:F})]});assert.equal(a.planDigest,b.planDigest);assert.deepEqual(a.operations,b.operations);});
test('duplicate record identities are rejected even when digests match',()=>{assert.throws(()=>planImmutablePublication({request:request(),records:[record(),record()]}),e=>e.code==='duplicate_identity');});
test('empty immutable publication is rejected',()=>{assert.throws(()=>planImmutablePublication({request:request(),records:[]}),e=>e.code==='missing_record');});
test('aggregate byte quota is enforced',()=>{assert.throws(()=>planImmutablePublication({request:request(),records:[record({bytes:20_000_001})]}),e=>e.code==='quota_exceeded');});
test('checkpoint count quota is enforced',()=>{const records=Array.from({length:9},(_,i)=>record({id:`checkpoint-${i}`}));assert.throws(()=>planImmutablePublication({request:request(),records}),e=>e.code==='quota_exceeded');});
test('export count quota is enforced',()=>{const records=Array.from({length:9},(_,i)=>record({kind:'export',id:`export-${i}`}));assert.throws(()=>planImmutablePublication({request:request(),records}),e=>e.code==='quota_exceeded');});
test('retention beyond 90 days is rejected',()=>{assert.throws(()=>planImmutablePublication({request:request(),records:[record({retentionDays:91})]}),e=>e.code==='invalid_integer');});
test('mutable pointer plan is exact CAS and pointer-last',()=>{const plan=planMutablePointerPublication({request:request(),current:{version:4,etag:D},pointer:{kind:'current',id:'checkpoint-index',digest:E,bytes:100}});assert.equal(plan.operations[0].ifMatch,D);assert.equal(plan.operations[0].phase,'pointer-last');assert.equal(plan.nextVersion,5);assert.match(plan.operations[0].key,/\/attempts\/attempt-a\/current\/checkpoint-index-v2\.json$/);});
test('mutable pointer rejects stale version or etag',()=>{assert.throws(()=>planMutablePointerPublication({request:request(),current:{version:3,etag:D},pointer:{kind:'current',id:'checkpoint-index',digest:E,bytes:100}}),e=>e.code==='stale_state');assert.throws(()=>planMutablePointerPublication({request:request(),current:{version:4,etag:F},pointer:{kind:'current',id:'checkpoint-index',digest:E,bytes:100}}),e=>e.code==='stale_state');});
test('publication plan validator accepts exact plan and rejects digest tampering',()=>{const plan=planImmutablePublication({request:request(),records:[record()]});assert.equal(validatePublicationPlan(plan).planDigest,plan.planDigest);assert.throws(()=>validatePublicationPlan({...plan,planDigest:F}),e=>e.code==='digest_mismatch');});
test('legacy digest recovery carries v2 exact identity and computes remaining work',()=>{const plan=planPublicationRecovery({request:request(),plannedDigests:[D,E,F],completedDigests:[D],failedStep:'checkpoint-index'});assert.equal(plan.attemptId,'attempt-a');assert.deepEqual(plan.remainingDigests,[E,F]);assert.equal(plan.retryPointerLast,true);assert.equal(plan.maxAttempts,4);});
test('legacy recovery rejects completion outside planned set',()=>{assert.throws(()=>planPublicationRecovery({request:request(),plannedDigests:[D,E],completedDigests:[F],failedStep:'checkpoint-index'}),e=>e.code==='recovery_conflict');});
test('legacy recovery rejects duplicate digest identities',()=>{assert.throws(()=>planPublicationRecovery({request:request(),plannedDigests:[D,D],completedDigests:[],failedStep:'checkpoint-index'}),e=>e.code==='duplicate_identity');});
test('typed scoped recovery preserves immutable index pointer order',()=>{const plan=planScopedPublicationRecovery({request:request(),plannedSteps:steps(),completedSteps:[steps()[0]],failedStep:'index-a'});assert.deepEqual(plan.retryOrder,['immutable','index-cas','pointer-last']);assert.deepEqual(plan.remainingSteps.map(x=>x.stepId),['index-a','pointer-a']);assert.equal(plan.attemptId,'attempt-a');assert.ok(Object.isFrozen(plan.remainingSteps));});
test('typed recovery rejects conflicting completed step evidence',()=>{const completed={...steps()[0],digest:F};assert.throws(()=>planScopedPublicationRecovery({request:request(),plannedSteps:steps(),completedSteps:[completed],failedStep:'immutable-a'}),e=>e.code==='recovery_conflict');});
test('typed recovery rejects pointer completion before immutable or index completion',()=>{assert.throws(()=>planScopedPublicationRecovery({request:request(),plannedSteps:steps(),completedSteps:[steps()[2]],failedStep:'pointer-a'}),e=>e.code==='pointer_order_conflict');});
test('typed recovery rejects duplicate planned step IDs',()=>{const planned=[steps()[0],{...steps()[1],stepId:'immutable-a'}];assert.throws(()=>planScopedPublicationRecovery({request:request(),plannedSteps:planned,completedSteps:[],failedStep:'immutable-a'}),e=>e.code==='duplicate_identity');});
test('typed recovery requires a v2 attempt-bound request',()=>{const legacy=service.createServiceRequest({operation:'fork.read',tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-a',forkId:'fork-a',mergeId:null,requesterId:'requester-a',scopes:['audit:read'],idempotencyKey:'legacy-a',expectedVersion:null,expectedEtag:null,requestedAt:AT,payload:{}});assert.throws(()=>planScopedPublicationRecovery({request:legacy,plannedSteps:steps(),completedSteps:[],failedStep:'immutable-a'}),e=>e.code==='scope_required');});
test('terminal lifecycle blocks write orchestration before publication',()=>{const req=request();assert.throws(()=>service.planPhase78Operation({request:req,authorization:{allowed:true},current:{version:4,etag:D,state:'cancelled',tenantId:'tenant-a',forkId:'fork-a',attemptId:'attempt-a'}}),e=>e.code==='terminal_state');});
test('publication outputs are recursively frozen and never use prefix listing',()=>{const immutable=planImmutablePublication({request:request(),records:[record()]});const pointer=planMutablePointerPublication({request:request(),current:{version:4,etag:D},pointer:{kind:'current',id:'checkpoint-index',digest:E,bytes:100}});for(const plan of [immutable,pointer]){assert.ok(Object.isFrozen(plan));assert.ok(Object.isFrozen(plan.operations));assert.equal(plan.usesPrefixListing,false);}});
