import test from 'node:test';
import assert from 'node:assert/strict';
import {
  ROUND4_INTAKE_SLOTS, SAFE_CAPABILITIES,
  createPublicInterfaceLock, assertPublicInterfaceCompatibility, composeReleaseCapabilities,
  validateSharedFileUnion, createComponentManifest, validateComponentManifest,
  createReleaseIntakePlan, createReleaseIntegrationManifest, validateReleaseIntegrationManifest
} from '../packages/audit-release-integration/src/index.mjs';

const SHA=(c)=>c.repeat(40);
const report=(issue=114,comment=5150000000)=>({issueNumber:issue,commentId:comment,url:`https://github.com/CurveYield/contract-automation/issues/${issue}#issuecomment-${comment}`});
function lock(id='phase1-6') { return createPublicInterfaceLock({componentId:id,schemaVersion:'phase1-6-public-v1',entrypoints:[`packages/${id}/src/index.mjs`],exports:['PHASE1_6_SCHEMA_VERSION','validatePhase1To6'],storagePrefixes:[`${id}/`],lifecycleOutcomes:['completed'],capabilities:SAFE_CAPABILITIES}); }
function operation(path,{source='b',destination=source,kind='exact',repairId=null}={}){return{path,sourceBlobSha:source===null?null:SHA(source),destinationBlobSha:destination===null?null:SHA(destination),adaptationKind:kind,repairId};}
function component(id='phase1-6',path=`packages/${id}/src/index.mjs`,options={}) { return createComponentManifest({componentId:id,issueNumber:114,branch:'audit-round3/phases1-8-release-integration-v1',finalSha:SHA('a'),status:'completed',recommendation:options.kind&&options.kind!=='exact'?'ACCEPT WITH REPAIR':'ACCEPT',report:report(),paths:[operation(path,options)],publicInterface:lock(id)}); }

test('Round 4 slots are exact and frozen',()=>{assert.deepEqual(ROUND4_INTAKE_SLOTS.map((x)=>x.issueNumber),[120,121,122,123,124]);assert.equal(Object.isFrozen(ROUND4_INTAKE_SLOTS),true);assert.deepEqual(ROUND4_INTAKE_SLOTS[2].stageBActivationIssues,[112,113,114,115,116,119,120,121,123,124]);});
test('hostile component manifests and dishonest exact blobs are rejected',()=>{const hostile={};Object.defineProperty(hostile,'componentId',{enumerable:true,get(){throw new Error('invoked')}});assert.throws(()=>createComponentManifest(hostile),(e)=>e.code==='accessor_field');assert.throws(()=>createComponentManifest({...component(),manifestDigest:undefined}),(e)=>['unknown_field','missing_field'].includes(e.code));assert.throws(()=>createComponentManifest({componentId:'x',issueNumber:1,branch:'a/b',finalSha:SHA('a'),status:'completed',recommendation:'ACCEPT',report:report(1,5150000001),paths:[operation('x/a',{source:'b',destination:'c'})],publicInterface:lock('x')}),(e)=>e.code==='invalid_adaptation');});
test('component manifests round-trip and bind per-path repairs',()=>{const exact=component();assert.equal(validateComponentManifest(exact).manifestDigest,exact.manifestDigest);const repaired=component('phase5','packages/phase5/src/common.mjs',{source:'b',destination:'c',kind:'repaired',repairId:'phase5-terminal-exit-null-v1'});assert.equal(repaired.paths[0].adaptationKind,'repaired');assert.deepEqual(repaired.ownedPaths,['packages/phase5/src/common.mjs']);assert.throws(()=>component('bad','packages/bad.mjs',{source:'b',destination:'c',kind:'repaired',repairId:null}),(e)=>e.code==='invalid_identifier');});
test('intake rejects protected paths and undeclared ownership overlaps',()=>{const a=component('a','packages/a/src/index.mjs');const b=component('b','packages/b/src/index.mjs');const plan=createReleaseIntakePlan({baseSha:SHA('1'),candidates:[b,a],protectedPaths:['packages/runner/src/run-job.mjs'],sharedUnions:[]});assert.deepEqual(plan.candidates.map((x)=>x.componentId),['a','b']);assert.throws(()=>createReleaseIntakePlan({baseSha:SHA('1'),candidates:[component('x','packages/runner/src')],protectedPaths:['packages/runner/src/run-job.mjs'],sharedUnions:[]}),(e)=>e.code==='protected_path');assert.throws(()=>createReleaseIntakePlan({baseSha:SHA('1'),candidates:[component('a','packages/shared'),component('b','packages/shared/file.mjs')],protectedPaths:[],sharedUnions:[]}),(e)=>e.code==='path_overlap');});
test('shared unions require disjoint fields and exact source/destination binding',()=>{const union=validateSharedFileUnion({schemaVersion:'audit-shared-file-union-v1',path:'package.json',baseBlobSha:SHA('1'),inputs:[{componentId:'a',blobSha:SHA('2'),fields:['exports.audit']},{componentId:'b',blobSha:SHA('3'),fields:['scripts.test']}],outputBlobSha:SHA('4'),strategy:'field-owned-v1'});assert.equal(union.inputs.length,2);assert.throws(()=>validateSharedFileUnion({...union,inputs:[{componentId:'a',blobSha:SHA('2'),fields:['exports']},{componentId:'b',blobSha:SHA('3'),fields:['exports.audit']}]}),(e)=>e.code==='union_field_overlap');const a=component('a','package.json',{source:'1',destination:'2',kind:'repaired',repairId:'package-a-v1'});const b=component('b','package.json',{source:'1',destination:'3',kind:'repaired',repairId:'package-b-v1'});assert.equal(createReleaseIntakePlan({baseSha:SHA('0'),candidates:[a,b],protectedPaths:[],sharedUnions:[union]}).sharedUnions.length,1);});
test('interface locks reject version and capability drift',()=>{const expected=lock();assert.equal(assertPublicInterfaceCompatibility(expected,expected).compatible,true);assert.throws(()=>assertPublicInterfaceCompatibility(expected,{...expected,schemaVersion:'phase1-6-public-v2'}),(e)=>e.code==='public_interface_drift');assert.throws(()=>createPublicInterfaceLock({componentId:'x',schemaVersion:'x-v1',entrypoints:['x/index.mjs'],exports:['validateX'],storagePrefixes:['x/'],lifecycleOutcomes:['completed'],capabilities:{...SAFE_CAPABILITIES,executionEnabled:true}}),(e)=>e.code==='capability_broadening');assert.equal(composeReleaseCapabilities([expected]).executionEnabled,false);});
test('release manifest locks protected blobs, stale inputs, capabilities, and Round 4 slots',()=>{const manifest=createReleaseIntegrationManifest({baseSha:SHA('1'),components:[component()],protectedBlobs:[{path:'packages/runner/src/run-job.mjs',blobSha:SHA('2')}],sharedUnions:[],staleInputs:['issue-97-phase7-8'],round4Slots:ROUND4_INTAKE_SLOTS});assert.equal(validateReleaseIntegrationManifest(manifest).releaseDigest,manifest.releaseDigest);assert.throws(()=>validateReleaseIntegrationManifest({...manifest,capabilities:{...manifest.capabilities,networkEnabled:true}}),(e)=>['capability_broadening','capability_drift'].includes(e.code));assert.throws(()=>createReleaseIntegrationManifest({baseSha:SHA('1'),components:[component()],protectedBlobs:[],sharedUnions:[],staleInputs:[],round4Slots:ROUND4_INTAKE_SLOTS.slice(1)}),(e)=>e.code==='round4_slot_mismatch');});
