import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const production=[
 'packages/audit-phase78-service/src/constants.mjs','packages/audit-phase78-service/src/contracts.mjs','packages/audit-phase78-service/src/authorization.mjs','packages/audit-phase78-service/src/orchestration.mjs','packages/audit-phase78-service/src/pagination.mjs','packages/audit-phase78-service/src/errors.mjs','packages/audit-phase78-service/src/index.mjs',
 'packages/audit-fork-reporting/src/common.mjs','packages/audit-fork-reporting/src/fork-projections.mjs','packages/audit-fork-reporting/src/checkpoint-projections.mjs','packages/audit-fork-reporting/src/delete-projection.mjs',
 'packages/audit-clean-room-reporting/src/campaign-merge.mjs','packages/audit-clean-room-reporting/src/relations.mjs','packages/audit-clean-room-reporting/src/provenance.mjs','packages/audit-clean-room-reporting/src/hidden.mjs',
 'packages/audit-phase78-publication/src/plans.mjs','packages/audit-phase78-publication/src/recovery.mjs'
];
const root=new URL('../',import.meta.url);
const text=Object.fromEntries(production.map(path=>[path,readFileSync(new URL(path,root),'utf8')]));
const joined=Object.values(text).join('\n');

test('owned production inventory is exact and duplicate-free',()=>{assert.equal(production.length,17);assert.equal(new Set(production).size,17);for(const path of production)assert.match(path,/^packages\/audit-(?:phase78-service|fork-reporting|clean-room-reporting|phase78-publication)\/src\//);});
test('production imports no Node-only or platform-specific modules',()=>{for(const [path,source] of Object.entries(text)){assert.doesNotMatch(source,/from\s+['"]node:/,path);assert.doesNotMatch(source,/\brequire\s*\(/,path);assert.doesNotMatch(source,/from\s+['"](?:fs|path|net|tls|dgram|child_process|worker_threads|cluster|os|http|https)['"]/,path);}});
test('production contains no process container or environment authority',()=>{for(const [path,source] of Object.entries(text)){assert.doesNotMatch(source,/\bprocess\s*\./,path);assert.doesNotMatch(source,/\bDeno\s*\./,path);assert.doesNotMatch(source,/\bBun\s*\./,path);assert.doesNotMatch(source,/\bspawn\s*\(|\bexecFile?\s*\(|\bfork\s*\(/,path);}});
test('production contains no network client or dynamic URL authority',()=>{for(const [path,source] of Object.entries(text)){assert.doesNotMatch(source,/\bfetch\s*\(|\bWebSocket\s*\(|\bXMLHttpRequest\b|\bEventSource\s*\(|sendBeacon\s*\(/,path);assert.doesNotMatch(source,/['"]https?:\/\//,path);}});
test('production contains no dynamic code execution',()=>{for(const [path,source] of Object.entries(text)){assert.doesNotMatch(source,/\beval\s*\(|new\s+Function\s*\(|\bimport\s*\(/,path);}});
test('production imports no storage internals or unscoped fork service',()=>{for(const [path,source] of Object.entries(text)){assert.doesNotMatch(source,/audit-forks\/src|audit-phase78-storage|object-store|r2-adapter|storage-adapter/,path);}});
test('execution and prefix listing remain fail-closed',()=>{assert.doesNotMatch(joined,/executionEnabled\s*:\s*true/);assert.doesNotMatch(joined,/usesPrefixListing\s*:\s*true/);assert.match(text['packages/audit-phase78-service/src/orchestration.mjs'],/executionEnabled:false/);assert.match(text['packages/audit-phase78-publication/src/plans.mjs'],/usesPrefixListing:false/);});
test('service v2 schemas and request-bound validators are exported',()=>{const contracts=text['packages/audit-phase78-service/src/contracts.mjs'];const index=text['packages/audit-phase78-service/src/index.mjs'];for(const token of ['audit-phase9-service-request-v2','audit-phase9-service-response-v2','audit-phase9-service-error-v2','validateServiceResponseForRequest','validateServiceErrorForRequest'])assert.match(contracts,new RegExp(token));assert.match(index,/export \* from '\.\/contracts\.mjs'/);assert.match(index,/export \* from '\.\/errors\.mjs'/);});
test('cursor and cache scope include attempt and visible-view identity',()=>{const source=text['packages/audit-phase78-service/src/pagination.mjs'];for(const token of ['campaignId','forkId','attemptId','mergeId','indexDigest','viewDigest','private, no-store','authorization','stale_cursor'])assert.match(source,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));const v2Return=source.match(/return frozenClone\(\{schemaVersion:'audit-phase9-page-v2',[^\n]+/u)?.[0]??'';assert.match(v2Return,/audit-phase9-page-v2/);assert.doesNotMatch(v2Return,/\btotal\s*:/);});
test('reports consume repaired public validators rather than raw trust',()=>{assert.match(text['packages/audit-fork-reporting/src/fork-projections.mjs'],/validateForkState/);assert.match(text['packages/audit-fork-reporting/src/checkpoint-projections.mjs'],/validateCheckpointManifest/);assert.match(text['packages/audit-fork-reporting/src/delete-projection.mjs'],/validateForkTombstone/);assert.match(text['packages/audit-clean-room-reporting/src/campaign-merge.mjs'],/validateTerminalCampaignManifest/);assert.match(text['packages/audit-clean-room-reporting/src/campaign-merge.mjs'],/validateMergeManifest/);assert.match(text['packages/audit-clean-room-reporting/src/relations.mjs'],/validateDuplicateRelation/);assert.match(text['packages/audit-clean-room-reporting/src/provenance.mjs'],/validateProvenanceIndex/);});
test('hidden report has no total or existence signal',()=>{const source=text['packages/audit-clean-room-reporting/src/hidden.mjs'];assert.doesNotMatch(source,/\btotal\s*:/);assert.doesNotMatch(source,/hiddenMembersPresent|exists\s*:/);assert.match(source,/resource_not_found/);});
test('publication is scope-bound CAS and pointer-last',()=>{const plans=text['packages/audit-phase78-publication/src/plans.mjs'];const recovery=text['packages/audit-phase78-publication/src/recovery.mjs'];for(const token of ['campaignId','forkId','attemptId','mergeId','ifNoneMatch','ifMatch','pointer-last'])assert.match(plans,new RegExp(token));for(const token of ['recovery_conflict','pointer_order_conflict','immutable','index-cas','pointer-last','maxAttempts:4'])assert.match(recovery,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});
test('production source contains no credential-shaped literal values',()=>{assert.doesNotMatch(joined,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/);assert.doesNotMatch(joined,/\bgh[pousr]_[A-Za-z0-9]{20,}\b/);assert.doesNotMatch(joined,/\bsk-[A-Za-z0-9]{20,}\b/);assert.doesNotMatch(joined,/AKIA[0-9A-Z]{16}/);});
