import test from 'node:test';
import assert from 'node:assert/strict';
import {
  ROUND4_INTAKE_SLOTS, SAFE_CAPABILITIES,
  createPublicInterfaceLock, assertPublicInterfaceCompatibility, composeReleaseCapabilities,
  validateSharedFileUnion, createComponentManifest, validateComponentManifest,
  createReleaseIntakePlan, createReleaseIntegrationManifest, validateReleaseIntegrationManifest
} from '../packages/audit-release-integration/src/index.mjs';

const SHA=(c)=>c.repeat(40);
function lock(id='phase1-6') { return createPublicInterfaceLock({componentId:id,schemaVersion:'v1',entrypoints:[`packages/${id}/src/index.mjs`],exports:['validate'],storagePrefixes:[`${id}/`],lifecycleOutcomes:['completed'],capabilities:SAFE_CAPABILITIES}); }
function component(id='phase1-6', path=`packages/${id}/src/index.mjs`, adaptation={kind:'exact',repairId:null}) { return createComponentManifest({componentId:id,issueNumber:114,branch:'audit-round3/phases1-8-release-integration-v1',finalSha:SHA('a'),status:'completed',recommendation:adaptation.kind==='exact'?'ACCEPT':'ACCEPT_WITH_REPAIR',reportUrl:'issue:114#comment',ownedPaths:[path],blobs:[{path,sourceBlobSha:SHA('b'),destinationBlobSha:adaptation.kind==='exact'?SHA('b'):SHA('c')}],publicInterface:lock(id),adaptation}); }

test('Round 4 slots are exact and frozen',()=>{assert.deepEqual(ROUND4_INTAKE_SLOTS.map((x)=>x.issueNumber),[120,121,122,123,124]);assert.equal(Object.isFrozen(ROUND4_INTAKE_SLOTS),true);});
test('hostile component manifests and dishonest exact blobs are rejected',()=>{const hostile={};Object.defineProperty(hostile,'componentId',{enumerable:true,get(){throw new Error('invoked')}});assert.throws(()=>createComponentManifest(hostile),(e)=>e.code==='accessor_field');assert.throws(()=>createComponentManifest({...component(),manifestDigest:undefined}),(e)=>['unknown_field','missing_field'].includes(e.code));assert.throws(()=>createComponentManifest({componentId:'x',issueNumber:1,branch:'a/b',finalSha:SHA('a'),status:'completed',recommendation:'ACCEPT',reportUrl:'issue:1',ownedPaths:['x/a'],blobs:[{path:'x/a',sourceBlobSha:SHA('b'),destinationBlobSha:SHA('c')}],publicInterface:lock('x'),adaptation:{kind:'exact',repairId:null}}),(e)=>e.code==='blob_mismatch');});
test('component manifests round-trip and repaired inputs require repair identity',()=>{const exact=component();assert.equal(validateComponentManifest(exact).manifestDigest,exact.manifestDigest);const repaired=component('phase5','packages/phase5/src/common.mjs',{kind:'repaired',repairId:'phase5-terminal-exit-null-v1'});assert.equal(repaired.adaptation.kind,'repaired');assert.throws(()=>component('bad','packages/bad.mjs',{kind:'repaired',repairId:null}),(e)=>e.code==='invalid_identifier');});
test('intake rejects protected paths and ownership overlaps',()=>{const a=component('a','packages/a/src/index.mjs');const b=component('b','packages/b/src/index.mjs');const plan=createReleaseIntakePlan({baseSha:SHA('1'),candidates:[b,a],protectedPaths:['packages/runner/src/run-job.mjs'],sharedUnions:[]});assert.deepEqual(plan.candidates.map((x)=>x.componentId),['a','b']);assert.throws(()=>createReleaseIntakePlan({baseSha:SHA('1'),candidates:[component('x','packages/runner/src/run-job.mjs')],protectedPaths:['packages/runner/src/run-job.mjs'],sharedUnions:[]}),(e)=>e.code==='protected_path');assert.throws(()=>createReleaseIntakePlan({baseSha:SHA('1'),candidates:[component('a','packages/shared'),component('b','packages/shared/file.mjs')],protectedPaths:[],sharedUnions:[]}),(e)=>e.code==='path_overlap');});
test('shared unions require disjoint field ownership',()=>{const good=validateSharedFileUnion({schemaVersion:'audit-shared-file-union-v1',path:'package.json',baseBlobSha:SHA('1'),inputs:[{componentId:'a',blobSha:SHA('2'),fields:['exports.audit']},{componentId:'b',blobSha:SHA('3'),fields:['scripts.test']}],outputBlobSha:SHA('4'),strategy:'field-owned-v1'});assert.equal(good.inputs.length,2);assert.throws(()=>validateSharedFileUnion({...good,inputs:[{componentId:'a',blobSha:SHA('2'),fields:['exports']},{componentId:'b',blobSha:SHA('3'),fields:['exports.audit']}]}),(e)=>e.code==='union_field_overlap');});
test('interface locks reject version and capability drift',()=>{const expected=lock();assert.equal(assertPublicInterfaceCompatibility(expected,expected).compatible,true);assert.throws(()=>assertPublicInterfaceCompatibility(expected,{...expected,schemaVersion:'v2'}),(e)=>e.code==='public_interface_drift');assert.throws(()=>createPublicInterfaceLock({componentId:'x',schemaVersion:'v1',entrypoints:['x/index.mjs'],exports:['x'],storagePrefixes:['x/'],lifecycleOutcomes:['completed'],capabilities:{...SAFE_CAPABILITIES,executionEnabled:true}}),(e)=>e.code==='capability_broadening');assert.equal(composeReleaseCapabilities([expected]).executionEnabled,false);});
test('release manifest locks protected blobs, stale inputs, capabilities, and Round 4 slots',()=>{const manifest=createReleaseIntegrationManifest({baseSha:SHA('1'),components:[component()],protectedBlobs:[{path:'packages/runner/src/run-job.mjs',blobSha:SHA('2')}],staleInputs:['issue-97-phase7-8'],round4Slots:ROUND4_INTAKE_SLOTS});assert.equal(validateReleaseIntegrationManifest(manifest).releaseDigest,manifest.releaseDigest);assert.throws(()=>validateReleaseIntegrationManifest({...manifest,capabilities:{...manifest.capabilities,networkEnabled:true}}),(e)=>['capability_broadening','capability_drift'].includes(e.code));assert.throws(()=>createReleaseIntegrationManifest({baseSha:SHA('1'),components:[component()],protectedBlobs:[],staleInputs:[],round4Slots:ROUND4_INTAKE_SLOTS.slice(1)}),(e)=>e.code==='round4_slot_mismatch');});
