import test from 'node:test';
import assert from 'node:assert/strict';
import {
  ROUND4_CANDIDATE_SLOTS, ROUND4_PRELIMINARY_OWNERSHIP, ROUND4_PROTECTED_BLOBS, ROUND4_INTAKE_WAVES,
  validateCompletedCandidateEvidence, validatePathOwnershipRegistry, validateRound4SharedUnion,
  validateIntakeWaveTemplate, validateRound5ProductionInput
} from '../packages/audit-integration-round4/src/index.mjs';

const SHA=(c)=>c.repeat(40);
const slot=()=>ROUND4_CANDIDATE_SLOTS[0];
const status=()=>({protocolVersion:1,workerId:'worker-0',state:'completed',lastConsumedSequence:6,activeSequence:null,activeMessageId:null,issueNumber:120,branch:'audit-round4/review-integration-spine-v1',startingSha:'5914b03382422ea714346625a601b5dbda3aa0cd',finalSha:SHA('a'),recommendation:'ACCEPT',reportReference:'https://github.com/CurveYield/contract-automation/issues/120#issuecomment-5150000120',blockers:[],updatedAt:'2026-08-02T10:00:00Z'});
const evidence=()=>({status:status(),resolvedBranchHead:SHA('a'),report:{issueNumber:120,commentId:5150000120,url:'https://github.com/CurveYield/contract-automation/issues/120#issuecomment-5150000120',finalSha:SHA('a'),recommendation:'ACCEPT'},manifests:[{schemaVersion:'round4-stage-a-review-manifest-v1',path:'docs/audit/round4/worker0/review-manifest-v1.json',blobSha:SHA('b')},{schemaVersion:'audit-release-component-manifest-v1',path:'docs/audit/round4/worker0/component-manifest-v1.json',blobSha:SHA('c')},{schemaVersion:'audit-public-interface-lock-v1',path:'docs/audit/round4/worker0/public-interface-lock-v1.json',blobSha:SHA('d')}]});

test('candidate slots are unresolved and frozen',()=>{assert.deepEqual(ROUND4_CANDIDATE_SLOTS.map((x)=>x.issueNumber),[120,121,123,124]);assert.ok(ROUND4_CANDIDATE_SLOTS.every((x)=>x.resolvedFinalSha===null));assert.ok(Object.isFrozen(ROUND4_CANDIDATE_SLOTS));});
test('completed evidence binds exact status, head, report and manifests',()=>{const value=validateCompletedCandidateEvidence(slot(),evidence());assert.equal(value.finalSha,SHA('a'));assert.equal(value.report.commentId,5150000120);assert.equal(value.manifests.length,3);});
test('stale, malformed and mismatched evidence is rejected',()=>{assert.throws(()=>validateCompletedCandidateEvidence(slot(),{...evidence(),status:{...status(),state:'working',finalSha:null}}),(e)=>e.code==='candidate_incomplete');assert.throws(()=>validateCompletedCandidateEvidence(slot(),{...evidence(),resolvedBranchHead:SHA('e')}),(e)=>e.code==='branch_head_mismatch');assert.throws(()=>validateCompletedCandidateEvidence(slot(),{...evidence(),status:{...status(),branch:'audit-round4/wrong-v1'}}),(e)=>e.code==='candidate_slot_mismatch');assert.throws(()=>validateCompletedCandidateEvidence(slot(),{...evidence(),report:{...evidence().report,commentId:5150000999}}),(e)=>e.code==='report_reference_mismatch');assert.throws(()=>validateCompletedCandidateEvidence(slot(),{...evidence(),manifests:evidence().manifests.slice(0,2)}),(e)=>e.code==='missing_manifest_schema');});
test('preliminary ownership covers all domains and protected paths',()=>{const value=validatePathOwnershipRegistry(ROUND4_PRELIMINARY_OWNERSHIP);assert.deepEqual(value.domains.map((x)=>x.domain),['api','github-direct','phase1-6-integration','phase7-8','web']);assert.equal(value.protectedPaths.length,ROUND4_PROTECTED_BLOBS.length);});
test('ownership rejects exact/nested overlap and protected mutation',()=>{const exact=structuredClone(ROUND4_PRELIMINARY_OWNERSHIP);exact.domains[1].ownedPrefixes=[exact.domains[0].ownedPrefixes[0]];assert.throws(()=>validatePathOwnershipRegistry(exact),(e)=>e.code==='ownership_overlap');const nested=structuredClone(ROUND4_PRELIMINARY_OWNERSHIP);nested.domains[1].ownedPrefixes=['apps/audit-api/internal'];assert.throws(()=>validatePathOwnershipRegistry(nested),(e)=>e.code==='ownership_overlap');const protectedValue=structuredClone(ROUND4_PRELIMINARY_OWNERSHIP);protectedValue.domains[0].ownedFiles=[ROUND4_PROTECTED_BLOBS[0].path];assert.throws(()=>validatePathOwnershipRegistry(protectedValue),(e)=>e.code==='protected_path');});
test('shared union binds order, fields, output and rerun tests',()=>{const union=validateRound4SharedUnion({schemaVersion:'round4-shared-file-union-v1',path:'package.json',baseBlobSha:SHA('1'),inputs:[{candidateId:'api-auth-reviewed',blobSha:SHA('2'),fields:['exports.auditApi']},{candidateId:'web-direct-reviewed',blobSha:SHA('3'),fields:['scripts.test:web']}],outputBlobSha:SHA('4'),requiredTests:['test/audit-round4-integration-api.test.mjs','test/audit-round4-integration-web.test.mjs']});assert.deepEqual(union.inputs.map((x)=>x.candidateId),['api-auth-reviewed','web-direct-reviewed']);assert.throws(()=>validateRound4SharedUnion({...union,inputs:[...union.inputs].reverse()}),(e)=>e.code==='noncanonical_union_order');assert.throws(()=>validateRound4SharedUnion({...union,inputs:[{candidateId:'api-auth-reviewed',blobSha:SHA('2'),fields:['exports']},{candidateId:'web-direct-reviewed',blobSha:SHA('3'),fields:['exports.auditApi']}]}),(e)=>e.code==='union_field_overlap');});
test('intake waves remain waiting while Stage A slots are unresolved',()=>{assert.deepEqual(ROUND4_INTAKE_WAVES.map((x)=>x.waveId),['phase1-8-core','api-auth','github-direct-web','protected-addon-final']);assert.equal(validateIntakeWaveTemplate(ROUND4_INTAKE_WAVES[0]).state,'waiting-for-stage-a');assert.throws(()=>validateIntakeWaveTemplate({...ROUND4_INTAKE_WAVES[0],state:'ready'}),(e)=>e.code==='premature_wave_state');});
test('Round 5 schema accepts names/caps only and forbids secret values or writable RPC',()=>{const value=validateRound5ProductionInput({schemaVersion:'round5-production-input-v1',secretNames:['CLOUDFLARE_API_TOKEN','PREFLIGHTSIM_CLIENT_API_KEY','RPC_ETHEREUM'],variableNames:['PREFLIGHTSIM_API_URL','PAGES_PROJECT_NAME'],cloudflare:{workerName:'curveyield-preflight-api',pagesProject:'curveyield-preflight',zones:['curveyield.online'],routes:['api.preflight.curveyield.online'],r2Bindings:[{binding:'AUDIT_R2',bucket:'curveyield-preflight'}],corsOrigins:['https://preflight.curveyield.online']},github:{repository:'CurveYield/contract-automation',environment:'production',workflowPath:'.github/workflows/audit-production-v1.yml'},rpcNetworks:[{name:'ethereum',secretName:'RPC_ETHEREUM',readOnly:true}],caps:{requestsPerMinute:30,dailyUsd:10,artifactBytes:10000000,retentionDays:7},rollback:{requiredChecks:['api-health','r2-read','web-health'],preservePreviousRelease:true},observability:{fields:['correlation-id','duration-ms','route','status'],redactions:['authorization','cookie','rpc-url']}});assert.ok(value.rpcNetworks[0].readOnly);assert.throws(()=>validateRound5ProductionInput({...value,secretNames:['CLOUDFLARE_API_TOKEN=secret']}),(e)=>e.code==='invalid_secret_name');assert.throws(()=>validateRound5ProductionInput({...value,rpcNetworks:[{name:'ethereum',secretName:'RPC_ETHEREUM',readOnly:false}]}),(e)=>e.code==='writable_rpc_forbidden');});
