import test from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryAuditStore } from '../packages/audit-r2-store/src/index.mjs';
import { tenantForkIndexKey } from '../packages/audit-fork-protocol/src/index.mjs';
import { ForkService } from '../packages/audit-forks/src/index.mjs';
const decoder=new TextDecoder();
class FailOnceStore{
  constructor(predicate){this.inner=new InMemoryAuditStore();this.predicate=predicate;this.failed=false;}
  async put(key,value,options){if(!this.failed&&this.predicate(key)){this.failed=true;throw new Error('simulated-partial-write');}return this.inner.put(key,value,options);}
  get(key){return this.inner.get(key);} head(key){return this.inner.head(key);} delete(key){return this.inner.delete(key);} usage(){return this.inner.usage();}
}
const ids={tenantId:'ten_'+'1'.repeat(32),workspaceId:'ws_'+'2'.repeat(32),campaignId:'cmp_'+'3'.repeat(32),forkId:'fork_'+'4'.repeat(32),attemptId:'att_'+'5'.repeat(32)};
function request(){return {schemaVersion:'fork-request-v1',...ids,profileId:'free-development-v1',policyVersion:'fork-policy-v1',requesterId:'usr',scopes:['audit:read','audit:submit'],chainId:1,blockNumber:21000000,blockHash:'0x'+'a'.repeat(64),adapterKind:'mock',executionGate:'trusted_mock',createdAt:'2026-08-01T00:00:00.000Z',idempotencyKey:'create'};}
function parse(record){return JSON.parse(typeof record.value==='string'?record.value:decoder.decode(record.value));}
test('create retry reconciles a partial tenant-index write without duplicating immutable records',async()=>{const store=new FailOnceStore((key)=>key.startsWith('indexes/tenant/'));const service=new ForkService(store);await assert.rejects(()=>service.createFork(request()),/simulated-partial-write/);const recovered=await service.createFork(request());assert.equal(recovered.state,'ready');const index=parse(await store.get(tenantForkIndexKey(ids.tenantId)));assert.equal(index.entries.length,1);assert.equal(index.entries[0].state,'ready');});
test('transition retry restores a missing immutable event and server-owned index state',async()=>{const store=new FailOnceStore((key)=>key.endsWith('/events/000000000003.json'));const service=new ForkService(store);const current=await service.createFork(request());const transition={forkId:ids.forkId,tenantId:ids.tenantId,attemptId:ids.attemptId,from:'ready',to:'checkpointing',expectedEtag:current.etag,transitionId:'tr_checkpoint_1',occurredAt:'2026-08-01T00:01:00.000Z'};await assert.rejects(()=>service.transitionFork(transition),/simulated-partial-write/);const recovered=await service.transitionFork(transition);assert.equal(recovered.state,'checkpointing');const index=parse(await store.get(tenantForkIndexKey(ids.tenantId)));assert.equal(index.entries[0].state,'checkpointing');});
test('operation traces classify every access and never enumerate storage',async()=>{const service=new ForkService(new InMemoryAuditStore());await service.createFork(request());const trace=service.operationTrace();assert.ok(trace.length>0);assert.equal(trace.some((entry)=>entry.method==='list'),false);assert.equal(trace.some((entry)=>entry.method==='copy'),false);for(const entry of trace) assert.match(entry.billingClass,/^(class-a|class-b|free)$/);});
test('fresh create trace is exactly six Class A and four Class B operations',async()=>{const service=new ForkService(new InMemoryAuditStore());await service.createFork(request());const counts=service.operationTrace().reduce((result,entry)=>{result[entry.billingClass]=(result[entry.billingClass]??0)+1;return result;},{});assert.deepEqual(counts,{'class-a':6,'class-b':4});});
