import test from 'node:test';
import assert from 'node:assert/strict';
import * as service from '../packages/audit-phase78-service/src/index.mjs';

const D=`sha256:${'1'.repeat(64)}`;
const E=`sha256:${'2'.repeat(64)}`;
const F=`sha256:${'3'.repeat(64)}`;
const AT='2026-08-02T11:00:00.000Z';

function forkRequest(overrides={}){
 return {
  operation:'fork.checkpoint',tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-a',
  forkId:'fork-a',attemptId:'attempt-a',mergeId:null,requesterId:'requester-a',scopes:['audit:submit'],
  idempotencyKey:'idem-a',expectedVersion:4,expectedEtag:D,requestedAt:AT,
  payload:{checkpointId:'checkpoint-a',manifestDigest:E},...overrides
 };
}
function legacyRead(){return {operation:'fork.read',tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-a',forkId:'fork-a',mergeId:null,requesterId:'requester-a',scopes:['audit:read'],idempotencyKey:'legacy-a',expectedVersion:null,expectedEtag:null,requestedAt:AT,payload:{}};}
function current(state='ready',overrides={}){return {version:4,etag:D,state,tenantId:'tenant-a',forkId:'fork-a',attemptId:'attempt-a',...overrides};}

test('legacy v1 service request remains valid',()=>{const request=service.createServiceRequest(legacyRead());assert.equal(request.schemaVersion,'audit-phase9-service-request-v1');assert.equal(service.validateServiceRequest(request).requestDigest,request.requestDigest);});
test('v2 service request binds immutable attempt identity',()=>{const request=service.createServiceRequest(forkRequest());assert.equal(request.schemaVersion,'audit-phase9-service-request-v2');assert.equal(request.attemptId,'attempt-a');assert.ok(Object.isFrozen(request));});
test('v2 fork request rejects missing attempt identity',()=>{assert.throws(()=>service.createServiceRequest({...forkRequest(),attemptId:null}),e=>e.code==='missing_identity');});
test('non-fork request rejects an attempt identity',()=>{assert.throws(()=>service.createServiceRequest({operation:'campaign.read',tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-a',forkId:null,attemptId:'attempt-a',mergeId:null,requesterId:'requester-a',scopes:['campaign:read'],idempotencyKey:'idem-b',expectedVersion:null,expectedEtag:null,requestedAt:AT,payload:{}}),e=>e.code==='identity_contradiction');});
test('v2 response carries exact request scope and is recursively frozen',()=>{const request=service.createServiceRequest(forkRequest());const response=service.createServiceResponse({request,status:'accepted',resourceId:'checkpoint-a',version:5,etag:E,body:{nested:{ok:true}},completedAt:AT});assert.equal(response.attemptId,'attempt-a');assert.equal(response.tenantId,'tenant-a');assert.ok(Object.isFrozen(response.body.nested));});
test('response-for-request validator rejects recomputed cross-tenant response',()=>{const request=service.createServiceRequest(forkRequest());const response=service.createServiceResponse({request,status:'accepted',resourceId:'checkpoint-a',version:5,etag:E,body:{ok:true},completedAt:AT});const core={...response,tenantId:'tenant-b'};delete core.responseDigest;const tampered={...core,responseDigest:service.sha256(core)};assert.throws(()=>service.validateServiceResponseForRequest(tampered,request),e=>e.code==='response_identity_mismatch');});
test('hidden absent cross-tenant and cross-attempt fork decisions are identical',()=>{const request=service.createServiceRequest({...forkRequest(),operation:'fork.read',scopes:['audit:read'],expectedVersion:null,expectedEtag:null,payload:{}});const absent=service.authorizePhase78Operation(request,{forkState:null});const tenant=service.authorizePhase78Operation(request,{forkState:{tenantId:'tenant-b',forkId:'fork-a',attemptId:'attempt-a'}});const attempt=service.authorizePhase78Operation(request,{forkState:{tenantId:'tenant-a',forkId:'fork-a',attemptId:'attempt-b'}});assert.deepEqual(tenant,absent);assert.deepEqual(attempt,absent);});
test('authorization does not invoke hostile state accessors',()=>{let invoked=0;const state={tenantId:'tenant-a',forkId:'fork-a'};Object.defineProperty(state,'attemptId',{enumerable:true,get(){invoked++;throw new Error('secret');}});const request=service.createServiceRequest({...forkRequest(),operation:'fork.read',scopes:['audit:read'],expectedVersion:null,expectedEtag:null,payload:{}});const decision=service.authorizePhase78Operation(request,{forkState:state});assert.equal(invoked,0);assert.equal(decision.reason,'resource_hidden');});
for(const [operation,payload,lifecycle,summary] of [['fork.checkpoint',{checkpointId:'checkpoint-a',manifestDigest:E},['ready','checkpointing','ready'],[9,10]],['fork.export',{checkpointId:'checkpoint-a',exportId:'export-a'},['ready','exporting','ready'],[8,12]],['fork.restore',{checkpointId:'checkpoint-a',restoreId:'restore-a',manifestDigest:E},['ready','restoring','ready'],[7,11]],['fork.delete',{reason:'cleanup'},['ready-or-transient','deleting','deleted'],[7,9]]]){test(`${operation} plan matches repaired lifecycle and measured counts`,()=>{const request=service.createServiceRequest(forkRequest({operation,payload}));const plan=service.planPhase78Operation({request,authorization:{allowed:true},current:current()});assert.deepEqual(plan.lifecycle,lifecycle);assert.equal(plan.operationSummary.classA,summary[0]);assert.equal(plan.operationSummary.classB,summary[1]);assert.equal(plan.executionEnabled,false);});}
test('checkpoint plan rejects a non-ready starting state',()=>{const request=service.createServiceRequest(forkRequest());assert.throws(()=>service.planPhase78Operation({request,authorization:{allowed:true},current:current('exporting')}),e=>e.code==='invalid_lifecycle_state');});
test('plan rejects attempt substitution in current state',()=>{const request=service.createServiceRequest(forkRequest());assert.throws(()=>service.planPhase78Operation({request,authorization:{allowed:true},current:current('ready',{attemptId:'attempt-b'})}),e=>e.code==='resource_identity_mismatch');});
function pageOptions(overrides={}){return {tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-a',forkId:'fork-a',attemptId:'attempt-a',mergeId:null,resourceKind:'checkpoint',indexDigest:D,viewDigest:E,pageSize:1,cursor:null,...overrides};}
const items=[{id:'a',createdAt:'2026-08-02T10:00:00.000Z',digest:D},{id:'b',createdAt:'2026-08-02T10:01:00.000Z',digest:E}];
test('v2 page omits total and returns scoped private cache metadata',()=>{const page=service.paginateDeterministically(items,pageOptions());assert.equal(Object.hasOwn(page,'total'),false);assert.equal(page.cacheMetadata.cacheControl,'private, no-store');assert.equal(page.cacheMetadata.vary,'authorization');});
test('cursor rejects a different attempt scope',()=>{const first=service.paginateDeterministically(items,pageOptions());assert.throws(()=>service.paginateDeterministically(items,pageOptions({attemptId:'attempt-b',cursor:first.nextCursor})),e=>e.code==='cursor_scope_mismatch');});
test('cursor rejects stale visible view and source index digests',()=>{const first=service.paginateDeterministically(items,pageOptions());assert.throws(()=>service.paginateDeterministically(items,pageOptions({viewDigest:F,cursor:first.nextCursor})),e=>e.code==='stale_cursor');assert.throws(()=>service.paginateDeterministically(items,pageOptions({indexDigest:F,cursor:first.nextCursor})),e=>e.code==='stale_cursor');});
test('cursor digest tampering is rejected',()=>{const first=service.paginateDeterministically(items,pageOptions());const cursor={...first.nextCursor,cursorDigest:F};assert.throws(()=>service.paginateDeterministically(items,pageOptions({cursor})),e=>e.code==='cursor_digest_mismatch');});
test('cache ETag changes with attempt and visible view scope',()=>{const scope=(overrides={})=>({tenantId:'tenant-a',workspaceId:'workspace-a',campaignId:'campaign-a',forkId:'fork-a',attemptId:'attempt-a',mergeId:null,resourceKind:'checkpoint',indexDigest:D,viewDigest:E,...overrides});const a=service.createScopedCacheMetadata(scope());const b=service.createScopedCacheMetadata(scope({attemptId:'attempt-b'}));const c=service.createScopedCacheMetadata(scope({viewDigest:F}));assert.notEqual(a.etag,b.etag);assert.notEqual(a.etag,c.etag);});
test('error normalization never invokes attacker-controlled accessors',()=>{let invoked=0;const hostile={};Object.defineProperty(hostile,'code',{enumerable:true,get(){invoked++;throw new Error('secret');}});const result=service.normalizePhase78ServiceError(hostile,{requestId:'svc-req-a',operation:'fork.read',at:AT});assert.equal(invoked,0);assert.equal(result.code,'internal_error');});
test('known internal not-found errors collapse to stable public not-found',()=>{const error=new Error('tenant b has checkpoint');error.code='checkpoint_not_found';const result=service.normalizePhase78ServiceError(error,{requestId:'svc-req-a',operation:'fork.read',at:AT});assert.deepEqual([result.code,result.message,result.path],['resource_not_found','Resource not found','$']);});
