import { exactKeys,enumValue,identifier,timestamp,createDirectState,validateDirectState,createDirectEvent,validateDirectEvent,validateDirectRequest,fail,DIRECT_STATES,frozenClone,denseArray,canonicalJson } from '../../audit-github-direct-protocol/src/index.mjs';
import { buildLedgerPaths,ledgerPathInfo } from './paths.mjs';
import { planImmutableCreate,planCasUpdate,validateLedgerMutation } from './mutations.mjs';
import { planJobIndexUpdate,validateJobIndex } from './index-state.mjs';
const terminal=new Set(['completed','failed','cancelled','policy_rejected','execution_plane_unavailable']);
const transitions={requested:['validating','cancelled'],validating:['admitted','failed','policy_rejected','cancelled'],admitted:['awaiting_executor','fixture_running','failed','cancelled'],awaiting_executor:['execution_plane_unavailable','cancelled'],fixture_running:['publishing','failed','cancelled'],publishing:['completed','failed'],completed:[],failed:[],cancelled:[],policy_rejected:[],execution_plane_unavailable:[]};
function mismatch(path){fail('transition_binding_mismatch',path,'Transition operations do not describe the same event and state');}
export function transitionLedgerState(input){const v=exactKeys(input,['request','currentState','currentBlobSha','indexBlobSha','to','reasonCode','at','currentIndex'],'$'),request=validateDirectRequest(v.request),current=validateDirectState(v.currentState),to=enumValue(v.to,DIRECT_STATES,'$.to'),reasonCode=identifier(v.reasonCode,'$.reasonCode'),at=timestamp(v.at,'$.at');if(current.jobId!==request.jobId||current.targetCommitSha!==request.targetCommitSha||current.repositoryId!==request.repositoryId||current.installationId!==request.installationId||current.repositoryFullName!==request.repositoryFullName)fail('request_state_mismatch','$.currentState');if(terminal.has(current.state))fail('terminal_state','$.currentState.state');if(!transitions[current.state].includes(to))fail('invalid_transition','$.to');const nextState=createDirectState({request,state:to,version:current.version+1,updatedAt:at}),event=createDirectEvent({request,from:current.state,to,version:nextState.version,reasonCode,at}),paths=buildLedgerPaths({jobId:request.jobId,eventId:event.eventId,resultId:'placeholder-result',reportId:'placeholder-report'}),eventPlan=planImmutableCreate({path:paths.event,content:event}),statePlan=planCasUpdate({path:paths.current,content:nextState,currentBlobSha:v.currentBlobSha,expectedBlobSha:v.currentBlobSha}),indexPlan=planJobIndexUpdate({currentIndex:v.currentIndex,currentBlobSha:v.indexBlobSha,expectedBlobSha:v.indexBlobSha,entry:{jobId:request.jobId,targetCommitSha:request.targetCommitSha,state:to,currentPath:paths.current,currentBlobSha:statePlan.nextContentBlobSha},updatedAt:at});return frozenClone({schemaVersion:'github-direct-ledger-transition-v1',nextState,event,operations:[eventPlan,statePlan,indexPlan]});}
export function validateLedgerTransition(input){
  const v=exactKeys(input,['schemaVersion','nextState','event','operations'],'$');if(v.schemaVersion!=='github-direct-ledger-transition-v1')fail('invalid_schema','$.schemaVersion');
  const nextState=validateDirectState(v.nextState),event=validateDirectEvent(v.event),operations=denseArray(v.operations,'$.operations',3).map((x)=>validateLedgerMutation(x));
  if(operations.length!==3||operations[0].operation!=='create-immutable'||operations[1].operation!=='update-cas'||operations[2].operation!=='update-cas')mismatch('$.operations');
  if(nextState.jobId!==event.jobId||nextState.targetCommitSha!==event.targetCommitSha||nextState.state!==event.to||nextState.version!==event.version||nextState.updatedAt!==event.at)mismatch('$.event');
  const eventInfo=ledgerPathInfo(operations[0].path,'$.operations[0].path'),currentInfo=ledgerPathInfo(operations[1].path,'$.operations[1].path'),indexInfo=ledgerPathInfo(operations[2].path,'$.operations[2].path');
  if(eventInfo.kind!=='event'||currentInfo.kind!=='current'||indexInfo.kind!=='job-index'||eventInfo.jobId!==nextState.jobId||eventInfo.eventId!==event.eventId||currentInfo.jobId!==nextState.jobId)mismatch('$.operations');
  if(canonicalJson(operations[0].content)!==canonicalJson(event)||canonicalJson(operations[1].content)!==canonicalJson(nextState))mismatch('$.operations');
  const index=validateJobIndex(operations[2].content),entry=index.entries.find((item)=>item.jobId===nextState.jobId);
  if(!entry||entry.targetCommitSha!==nextState.targetCommitSha||entry.state!==nextState.state||entry.currentPath!==operations[1].path||entry.currentBlobSha!==operations[1].nextContentBlobSha||index.updatedAt!==nextState.updatedAt)mismatch('$.operations[2].content');
  return frozenClone({schemaVersion:v.schemaVersion,nextState,event,operations});
}
