import {
  DIRECT_MODE_ID,exactKeys,validateDirectRequest,timestamp,createResultManifest,validateResultManifest,
  denseArray,enumValue,booleanValue,identifier,digest,sha256,frozenClone,fail
} from '../../audit-github-direct-protocol/src/index.mjs';
import { validateRunnerAdmission } from './admission.mjs';
export function orchestrateDirectJob(input){
  const v=exactKeys(input,['request','admission','producedAt'],'$'),request=validateDirectRequest(v.request),admission=validateRunnerAdmission(v.admission),producedAt=timestamp(v.producedAt,'$.producedAt');
  if(admission.jobId!==request.jobId||admission.targetCommitSha!==request.targetCommitSha||admission.repositoryId!==request.repositoryId||admission.installationId!==request.installationId||admission.repositoryFullName!==request.repositoryFullName)fail('admission_request_mismatch','$.admission');
  const fixture=admission.fixtureId!==null;
  const resultManifest=createResultManifest({request,outcome:fixture?'modeled_fixture':'execution_unavailable',executionState:fixture?'fixture_modeled':'execution_plane_unavailable',resultDigest:fixture?admission.modeledResultDigest:null,summary:admission.summary,producedAt});
  const core={schemaVersion:'github-direct-runner-outcome-v1',modeId:DIRECT_MODE_ID,jobId:request.jobId,targetCommitSha:request.targetCommitSha,fixtureId:admission.fixtureId,terminalState:fixture?'completed':'execution_plane_unavailable',transitions:fixture?['admitted','fixture_running','publishing','completed']:['admitted','awaiting_executor','execution_plane_unavailable'],executionPerformed:false,resultManifest,producedAt};
  const outcomeDigest=sha256(core);return frozenClone({...core,outcomeId:`direct-outcome-${outcomeDigest.slice(7,31)}`,outcomeDigest});
}
export function validateRunnerOutcome(input){
  const v=exactKeys(input,['schemaVersion','modeId','jobId','targetCommitSha','fixtureId','terminalState','transitions','executionPerformed','resultManifest','producedAt','outcomeId','outcomeDigest'],'$');if(v.schemaVersion!=='github-direct-runner-outcome-v1')fail('invalid_schema','$.schemaVersion');if(v.modeId!==DIRECT_MODE_ID)fail('invalid_mode','$.modeId');identifier(v.jobId,'$.jobId');commitShaShim(v.targetCommitSha,'$.targetCommitSha');const fixtureId=v.fixtureId===null?null:identifier(v.fixtureId,'$.fixtureId');const terminalState=enumValue(v.terminalState,['completed','execution_plane_unavailable'],'$.terminalState');const transitions=denseArray(v.transitions,'$.transitions',4).map((x,i)=>enumValue(x,['admitted','awaiting_executor','execution_plane_unavailable','fixture_running','publishing','completed'],`$.transitions[${i}]`));if(booleanValue(v.executionPerformed,'$.executionPerformed')!==false)fail('execution_boundary_violation','$.executionPerformed');const resultManifest=validateResultManifest(v.resultManifest);timestamp(v.producedAt,'$.producedAt');digest(v.outcomeDigest,'$.outcomeDigest');const expectedTransitions=fixtureId===null?['admitted','awaiting_executor','execution_plane_unavailable']:['admitted','fixture_running','publishing','completed'];if(JSON.stringify(transitions)!==JSON.stringify(expectedTransitions))fail('transition_mismatch','$.transitions');if((fixtureId===null&&terminalState!=='execution_plane_unavailable')||(fixtureId!==null&&terminalState!=='completed'))fail('outcome_contradiction','$.terminalState');if(resultManifest.jobId!==v.jobId||resultManifest.targetCommitSha!==v.targetCommitSha)fail('result_identity_mismatch','$.resultManifest');const core={schemaVersion:v.schemaVersion,modeId:v.modeId,jobId:v.jobId,targetCommitSha:v.targetCommitSha,fixtureId,terminalState,transitions,executionPerformed:false,resultManifest,producedAt:v.producedAt};const expected=sha256(core);if(v.outcomeDigest!==expected)fail('digest_mismatch','$.outcomeDigest');if(v.outcomeId!==`direct-outcome-${expected.slice(7,31)}`)fail('identity_mismatch','$.outcomeId');return frozenClone(v);
}
function commitShaShim(value,path){if(typeof value!=='string'||!/^[0-9a-f]{40}$/.test(value))fail('invalid_commit_sha',path);return value;}
