import { exactKeys,identifier,digest,timestamp,enumValue,denseArray,frozenClone,fail,boolean,nullable,validateCampaignAccessContext,validateShareGrant,validateShareGrantRevocation } from '../../audit-clean-room-protocol/src/index.mjs';
import { VISIBILITY_DECISION_SCHEMA,RESOURCE_KINDS,REASONS } from './constants.mjs';
import { readAuthorizationReason } from './authorization.mjs';
function validateGrants(value){return denseArray(value,'$.grants',10_000).map((entry)=>validateShareGrant(entry));}
function validateRevocations(value){return denseArray(value,'$.revocations',10_000).map((entry)=>validateShareGrantRevocation(entry));}
function revoked(grant,revocations,at){return revocations.some((value)=>value.grantId===grant.grantId&&value.grantDigest===grant.grantDigest&&value.revokedAt<=at);}
export function decideResourceVisibility(input){const v=exactKeys(input,['context','resource','grants','revocations','at'],'$');const context=validateCampaignAccessContext(v.context);const resourceRaw=exactKeys(v.resource,['kind','tenantId','workspaceId','campaignId','resourceId','resourceDigest','sourceDigest'],'$.resource');const resource={kind:enumValue(resourceRaw.kind,RESOURCE_KINDS,'$.resource.kind'),tenantId:identifier(resourceRaw.tenantId,'$.resource.tenantId'),workspaceId:identifier(resourceRaw.workspaceId,'$.resource.workspaceId'),campaignId:identifier(resourceRaw.campaignId,'$.resource.campaignId'),resourceId:identifier(resourceRaw.resourceId,'$.resource.resourceId'),resourceDigest:digest(resourceRaw.resourceDigest,'$.resource.resourceDigest'),sourceDigest:digest(resourceRaw.sourceDigest,'$.resource.sourceDigest')};const grants=validateGrants(v.grants),revocations=validateRevocations(v.revocations),at=timestamp(v.at,'$.at');let visible=false,reason='resource_hidden',grantId=null;const readReason=readAuthorizationReason(context);if(readReason!=='allowed')reason=readReason;else if(context.tenantId===resource.tenantId&&context.workspaceId===resource.workspaceId&&context.campaignId===resource.campaignId){visible=true;reason='allowed';}else if(context.tenantId===resource.tenantId&&context.workspaceId===resource.workspaceId&&resource.kind==='base_artifact'){for(const grant of grants){if(grant.tenantId===context.tenantId&&grant.workspaceId===context.workspaceId&&grant.targetCampaignId===context.campaignId&&grant.sourceCampaignId===resource.campaignId&&grant.artifactId===resource.resourceId&&grant.artifactDigest===resource.resourceDigest&&grant.sourceDigest===resource.sourceDigest){if(grant.expiresAt<=at){reason='grant_expired';continue;}if(revoked(grant,revocations,at)){reason='grant_revoked';continue;}visible=true;reason='allowed';grantId=grant.grantId;break;}}if(!visible&&reason==='resource_hidden')reason='grant_missing';}
return frozenClone({schemaVersion:VISIBILITY_DECISION_SCHEMA,visible,reason,resourceKind:resource.kind,tenantId:context.tenantId,workspaceId:context.workspaceId,campaignId:context.campaignId,resourceId:visible?resource.resourceId:null,grantId,decidedAt:at});}
export function validateVisibilityDecision(input){const v=exactKeys(input,['schemaVersion','visible','reason','resourceKind','tenantId','workspaceId','campaignId','resourceId','grantId','decidedAt'],'$');if(v.schemaVersion!==VISIBILITY_DECISION_SCHEMA)fail('invalid_schema','$.schemaVersion');const visible=boolean(v.visible,'$.visible'),reason=enumValue(v.reason,REASONS,'$.reason');if(visible!==(reason==='allowed'))fail('decision_contradiction','$.visible');const result={schemaVersion:v.schemaVersion,visible,reason,resourceKind:enumValue(v.resourceKind,RESOURCE_KINDS,'$.resourceKind'),tenantId:identifier(v.tenantId,'$.tenantId'),workspaceId:identifier(v.workspaceId,'$.workspaceId'),campaignId:identifier(v.campaignId,'$.campaignId'),resourceId:nullable(v.resourceId,identifier,'$.resourceId'),grantId:nullable(v.grantId,identifier,'$.grantId'),decidedAt:timestamp(v.decidedAt,'$.decidedAt')};if(!visible&&(result.resourceId!==null||result.grantId!==null))fail('hidden_resource_leak','$.resourceId');return frozenClone(result);}
