import {
  exactKeys,plainObject,integer,fullName,commitSha,boundedString,booleanValue,
  enumValue,nullable,frozenClone,fail
} from '../../audit-github-direct-protocol/src/index.mjs';
import { blobSha } from '../../audit-github-direct-ledger/src/index.mjs';

function exactVariant(value,variants,path='$'){
  const desc=plainObject(value,path);const actual=Object.keys(desc).sort();
  for(const keys of variants){const expected=[...keys].sort();if(JSON.stringify(actual)===JSON.stringify(expected))return exactKeys(value,keys,path);}
  fail('invalid_transport_response',path);
}
export function validateRepositoryResponse(value,bound){const v=exactKeys(value,['repositoryId','fullName'],'$.transportResult');const result={repositoryId:integer(v.repositoryId,'$.transportResult.repositoryId',1),fullName:fullName(v.fullName,'$.transportResult.fullName')};if(result.repositoryId!==bound.repositoryId||result.fullName!==bound.repositoryFullName)fail('transport_identity_mismatch','$.transportResult');return frozenClone(result);}
export function validateCommitResponse(value,bound){const v=exactKeys(value,['sha'],'$.transportResult'),sha=commitSha(v.sha,'$.transportResult.sha');if(sha!==bound.targetCommitSha)fail('transport_identity_mismatch','$.transportResult.sha');return frozenClone({sha});}
export function validateBlobResponse(value,wanted){const v=exactKeys(value,['blobSha','sizeBytes'],'$.transportResult'),result={blobSha:blobSha(v.blobSha,'$.transportResult.blobSha'),sizeBytes:integer(v.sizeBytes,'$.transportResult.sizeBytes',0,2_000_000_000)};if(result.blobSha!==wanted)fail('transport_identity_mismatch','$.transportResult.blobSha');return frozenClone(result);}
export function validateContentsResponse(value,wantedPath,bound){const v=exactVariant(value,[['path','blobSha'],['path','blobSha','content','ref']],'$.transportResult');const path=boundedString(v.path,'$.transportResult.path',512);if(path!==wantedPath)fail('transport_identity_mismatch','$.transportResult.path');const result={path,blobSha:blobSha(v.blobSha,'$.transportResult.blobSha')};if(Object.hasOwn(v,'content')){const ref=boundedString(v.ref,'$.transportResult.ref',128);const expected=wantedPath.startsWith('.audit-direct/v1/')?'audit-direct/control-v1':bound.targetCommitSha;if(ref!==expected)fail('transport_identity_mismatch','$.transportResult.ref');result.content=v.content;result.ref=ref;}return frozenClone(result);}
export function validateLedgerMutationResponse(value,mutation){const v=exactVariant(value,[['applied','nextBlobSha'],['applied','nextBlobSha','commitSha']],'$.transportResult');const result={applied:booleanValue(v.applied,'$.transportResult.applied'),nextBlobSha:blobSha(v.nextBlobSha,'$.transportResult.nextBlobSha')};if(Object.hasOwn(v,'commitSha'))result.commitSha=nullable(v.commitSha,commitSha,'$.transportResult.commitSha');return frozenClone(result);}
export function validatePublicationResponse(value,plan){const v=exactVariant(value,[['published','publicationId'],['action','publicationId'],['action','publicationId','githubId']],'$.transportResult');const publicationId=boundedString(v.publicationId,'$.transportResult.publicationId',128);if(publicationId!==plan.publicationId)fail('transport_identity_mismatch','$.transportResult.publicationId');if(Object.hasOwn(v,'published')){if(booleanValue(v.published,'$.transportResult.published')!==true)fail('invalid_transport_response','$.transportResult.published');return frozenClone({published:true,publicationId});}const action=enumValue(v.action,['create'],'$.transportResult.action');const result={action,publicationId};if(Object.hasOwn(v,'githubId'))result.githubId=v.githubId===null?null:integer(v.githubId,'$.transportResult.githubId',1);return frozenClone(result);}
