import test from 'node:test';import assert from 'node:assert/strict';
import {PHASE6_PROFILE_TEMPLATES,publishPhase6Profile} from '../../audit-phase6-profile-contracts/src/index.mjs';
import {PHASE6_TOOL_CATALOG_VERSION,createPhase6ToolCatalog,validatePhase6ToolCatalog} from '../src/index.mjs';
const pub=(id,ch='a')=>publishPhase6Profile(id,{imageDigest:`sha256:${ch.repeat(64)}`,releaseIdentifier:PHASE6_PROFILE_TEMPLATES[id].versions.tool.releaseIdentifier});

test('creates exact sorted read-only catalog without fabricated publication data',()=>{assert.equal(PHASE6_TOOL_CATALOG_VERSION,'phase6-tool-catalog-v1');const c=createPhase6ToolCatalog();assert.deepEqual(c.entries.map(x=>x.profileId),['formal-obligations-v1','halmos-v1','solidity-smt-v1']);for(const e of c.entries){assert.equal(e.digestRequired,true);assert.equal(e.publication.status,'unpublished');assert.equal(e.publication.imageDigest,null);assert.equal(e.runnable,false);assert.equal(e.executionEnabled,false);assert.equal(e.executor.available,false);}assert.equal(Object.isFrozen(c),true);});

test('admits only canonically published profiles and preserves disabled state',()=>{const c=createPhase6ToolCatalog([pub('halmos-v1','b'),pub('solidity-smt-v1','c')]);const h=c.entries.find(x=>x.profileId==='halmos-v1');assert.equal(h.publication.status,'published');assert.equal(h.publication.imageDigest,`sha256:${'b'.repeat(64)}`);assert.equal(h.digestRequired,false);assert.equal(h.runnable,false);assert.equal(h.executionEnabled,false);assert.deepEqual(validatePhase6ToolCatalog(c),c);});

test('rejects duplicate, unknown, custom-prototype and publication identity drift',()=>{assert.throws(()=>createPhase6ToolCatalog([pub('halmos-v1'),pub('halmos-v1')]),e=>e.code==='duplicate_profile');const unknown=structuredClone(pub('halmos-v1'));unknown.profileId='unknown';assert.throws(()=>createPhase6ToolCatalog([unknown]),e=>e.code==='unknown_profile_id');const custom=Object.create({x:true});Object.assign(custom,pub('halmos-v1'));assert.throws(()=>createPhase6ToolCatalog([custom]),e=>e.code==='invalid_plain_object');const drift=structuredClone(pub('halmos-v1'));drift.versions.tool.version='9.9.9';assert.throws(()=>createPhase6ToolCatalog([drift]),e=>e.code==='publication_identity_drift');});

test('catalog preserves exact tool compiler solver and release identities without timestamps',()=>{const c=createPhase6ToolCatalog();for(const entry of c.entries){const template=PHASE6_PROFILE_TEMPLATES[entry.profileId];assert.deepEqual(entry.versions,template.versions,entry.profileId);assert.deepEqual(entry.compatibility,template.compatibility,entry.profileId);assert.equal(Object.hasOwn(entry.publication,'publishedAt'),false,entry.profileId);assert.equal(Object.isFrozen(entry),true,entry.profileId);assert.equal(Object.isFrozen(entry.versions),true,entry.profileId);assert.equal(entry.parserIdentity.function.length>0,true);}});

test('publication and catalog one-field drift fail deterministically',()=>{const release=structuredClone(pub('halmos-v1'));release.publication.releaseIdentifier='latest';assert.throws(()=>createPhase6ToolCatalog([release]),e=>e.code==='invalid_release_identifier');const digest=structuredClone(pub('halmos-v1'));digest.publication.imageDigest='sha256:bad';assert.throws(()=>createPhase6ToolCatalog([digest]),e=>e.code==='invalid_image_digest');const c=structuredClone(createPhase6ToolCatalog());c.entries[0].parserIdentity.function='other';assert.throws(()=>validatePhase6ToolCatalog(c),e=>e.code==='catalog_identity_drift'&&e.path==='$');const enabled=structuredClone(createPhase6ToolCatalog());enabled.entries[0].executionEnabled=true;assert.throws(()=>validatePhase6ToolCatalog(enabled),e=>e.code==='catalog_identity_drift'&&e.path==='$');});
