import test from 'node:test';import assert from 'node:assert/strict';
import {PHASE6_PROFILE_TEMPLATES,publishPhase6Profile} from '../../audit-phase6-profile-contracts/src/index.mjs';
import {createPhase6ToolResultEnvelope,validatePhase6ToolResult} from '../../audit-phase6-result-contracts/src/index.mjs';
import {createPhase6ToolCatalog,validatePhase6ToolCatalog,assertPhase6PackageCompatibility} from '../src/index.mjs';
import {resultFor} from '../../audit-phase6-result-contracts/test/helpers.mjs';
const assertError=(fn,code,path)=>assert.throws(fn,e=>e?.code===code&&e?.path===path,`${code}:${path}`);
const result=()=>createPhase6ToolResultEnvelope('solidity-smt-v1',resultFor('solidity-smt-proof-v2.json'));

test('compatibility accepts an explicit canonical catalog and publication set',()=>{const published=publishPhase6Profile('halmos-v1',{imageDigest:`sha256:${'a'.repeat(64)}`,releaseIdentifier:PHASE6_PROFILE_TEMPLATES['halmos-v1'].versions.tool.releaseIdentifier});const catalog=createPhase6ToolCatalog([published]);const checked=assertPhase6PackageCompatibility({catalog,publishedProfiles:[published],results:[result()]});assert.equal(checked.checkedCatalogEntries,3);assert.equal(checked.checkedPublishedProfiles,1);});

test('every public result-envelope field rejects one-field deletion deterministically',()=>{for(const key of Object.keys(result())){const value=structuredClone(result());delete value[key];assertError(()=>validatePhase6ToolResult(value),'missing_field',`$.${key}`);}});

test('every formal-result and summary field rejects one-field deletion deterministically',()=>{for(const key of Object.keys(result().result)){const value=structuredClone(result());delete value.result[key];assertError(()=>validatePhase6ToolResult(value),'missing_field',`$.result.${key}`);}for(const key of Object.keys(result().summary)){const value=structuredClone(result());delete value.summary[key];assertError(()=>validatePhase6ToolResult(value),'missing_field',`$.summary.${key}`);}});

test('every public catalog field and entry field rejects one-field deletion deterministically',()=>{const catalog=createPhase6ToolCatalog();for(const key of Object.keys(catalog)){const value=structuredClone(catalog);delete value[key];assertError(()=>validatePhase6ToolCatalog(value),'missing_field',`$.${key}`);}for(const key of Object.keys(catalog.entries[0])){const value=structuredClone(catalog);delete value.entries[0][key];assertError(()=>validatePhase6ToolCatalog(value),'missing_field',`$.entries[0].${key}`);}});

test('identity lifecycle evidence publication and truncation substitutions fail through compatibility',()=>{const vectors=[];for(const [key,value] of [['profileId','halmos-v1'],['parserId','parseHalmosBytes'],['toolVersion','0.3.3'],['captureSchemaVersion','halmos-capture-v1'],['resultSchemaVersion','other'],['trustedProducer','other']]){const x=structuredClone(result());x[key]=value;vectors.push([x,'identity_mismatch',key==='profileId'?'$.results[0].result.profileId':`$.results[0].${key}`]);}const outcome=structuredClone(result());outcome.outcome='disproved';vectors.push([outcome,'outcome_mismatch','$.results[0].outcome']);const evidence=structuredClone(result());evidence.result.outcome='disproved';evidence.outcome='disproved';vectors.push([evidence,'outcome_evidence_mismatch','$.results[0].result.counterexamples']);const summary=structuredClone(result());summary.summary.obligations+=1;vectors.push([summary,'summary_mismatch','$.results[0].summary.obligations']);for(const [value,code,path] of vectors)assertError(()=>assertPhase6PackageCompatibility({results:[value]}),code,path);const catalog=structuredClone(createPhase6ToolCatalog());catalog.entries[0].publication.releaseIdentifier='drift';assertError(()=>assertPhase6PackageCompatibility({catalog}),'catalog_identity_drift','$.catalog');});
